bows_url_db = {
	0 = {
		name = "Sentinel's Recurve",
		location = "Darkshore",
		source = "Aman",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "0.21",
		id = "0",
	},
	1 = {
		name = "Bow of Virulent Infection",
		location = "Uldir",
		source = "Vectis",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Battle For Azeroth",
		drop_rate = "1.12",
		id = "1",
	},
	2 = {
		name = "Yang's Other Recurve",
		location = "Nazmir",
		source = "Blood Troll Hexxer",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "0.01",
		id = "2",
	},
	3 = {
		name = "Pterrorwing Longbow",
		location = "Battle of Dazar'alor",
		source = "Pakus Aspect",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Battle For Azeroth",
		drop_rate = "Unknown",
		id = "3",
	},
	4 = {
		name = "Hallowed Ossein Longbow",
		location = "Atal'Dazar",
		source = "Rezan",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Battle For Azeroth",
		drop_rate = "Unknown",
		id = "4",
	},
	5 = {
		name = "Snakebite Recurve",
		location = "Temple of Sethraliss",
		source = "Merektha",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Battle For Azeroth",
		drop_rate = "0.88",
		id = "5",
	},
	6 = {
		name = "Evergreen Scout's Bow",
		location = "Nazmir",
		source = "Scout Skrasniss",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "6.01",
		id = "6",
	},
	7 = {
		name = "Honorbound Longbow",
		location = "Arathi Highlands",
		source = "Beastrider Kama",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "0.15",
		id = "7",
	},
	8 = {
		name = "7th Legionnaire's Longbow",
		location = "Arathi Highlands",
		source = "Skullripper",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "0.15",
		id = "8",
	},
	9 = {
		name = "Bleached Bone Longbow",
		location = "Zuldazar",
		source = "Zandalari Hexxer",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "0.06",
		id = "9",
	},
	10 = {
		name = "Rivermarsh Composite",
		location = "The MOTHERLODE!!",
		source = "Taskmaster Askari",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Legion",
		drop_rate = "0.06",
		id = "10",
	},
	11 = {
		name = "Warport Short Bow",
		location = "Vol'dun",
		source = "Golanar",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "0.07",
		id = "11",
	},
	12 = {
		name = "Golden Fleet Bow",
		location = "Nazmir",
		source = "Faceless Destroyer",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "0.07",
		id = "12",
	},
	13 = {
		name = "Shadow Hunter's Bow",
		location = "Orgrimmar",
		source = "Hour of Reckoning",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "13",
	},
	14 = {
		name = "Longbow of the Hunt",
		location = "Stormwind City",
		source = "Hour of Reckoning",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "14",
	},
	15 = {
		name = "Death's Hunter Greatbow",
		location = "Nazmir",
		source = "Soulbound",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "15",
	},
	16 = {
		name = "Jam'jen's Shortbow",
		location = "Vol'dun",
		source = "Zandalari Treasure Trove",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "16",
	},
	17 = {
		name = "Fallen Nation Recurve",
		location = "Nazmir",
		source = "Containment Procedure",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "17",
	},
	18 = {
		name = "Crawgmother's Shortbow",
		location = "Nazmir",
		source = "Off With Her Head",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "18",
	},
	19 = {
		name = "Pa'ku-Blessed Greatbow",
		location = "Zuldazar",
		source = "Dire Situation",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "19",
	},
	20 = {
		name = "Venom Queen Longbow",
		location = "Zuldazar",
		source = "Mistress of Lies",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "20",
	},
	21 = {
		name = "Rootway Safari Greatbow",
		location = "Zuldazar",
		source = "Headhunter Jo",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "21",
	},
	22 = {
		name = "Sezahjin's Vulture Bow",
		location = "Vol'dun",
		source = "Mojambo",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "22",
	},
	23 = {
		name = "Spireguard's Greatbow",
		location = "Vol'dun",
		source = "The Fall of Emperor Korthek",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "23",
	},
	24 = {
		name = "Sethrak Sandscout's Bow",
		location = "Vol'dun",
		source = "An Explosive Exit",
		territory = "Horde",
		category_territory = "Outdoor Zone",
		expansion = "Battle For Azeroth",
		drop_rate = "quest",
		id = "24",
	},
	25 = {
		name = "Huntmaster's Longbow",
		location = "Trueshot Lodge",
		source = "Outfitter Reynolds",
		territory = "",
		category_territory = "",
		expansion = "Legion",
		drop_rate = "Unknown",
		id = "25",
	},
	26 = {
		name = "Warmongering Gladiator's Longbow",
		location = "Stormshield",
		source = "Holly McTilla",
		territory = "War Zone",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "26",
	},
	27 = {
		name = "Warmongering Gladiator's Longbow",
		location = "Warspear",
		source = "Malukah Lightsong",
		territory = "Alliance",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "27",
	},
	28 = {
		name = "Cursed Demonbone Longbow",
		location = "Hellfire Citadel",
		source = "Mannoroth",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Warlords Of Draenor",
		drop_rate = "14.18",
		id = "28",
	},
	29 = {
		name = "Wild Gladiator's Longbow",
		location = "Stormshield",
		source = "Amelia Clarke",
		territory = "War Zone",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "29",
	},
	30 = {
		name = "Wild Gladiator's Longbow",
		location = "Warspear",
		source = "Cladd Dawnstrider",
		territory = "Alliance",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "30",
	},
	31 = {
		name = "Warmongering Combatant's Longbow",
		location = "Stormshield",
		source = "Li",
		territory = "War Zone",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "31",
	},
	32 = {
		name = "Warmongering Combatant's Longbow",
		location = "Warspear",
		source = "Taeloxe Soulshrivel",
		territory = "Alliance",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "32",
	},
	33 = {
		name = "Snarlwood Recurve Bow",
		location = "Hellfire Citadel",
		source = "Mannoroth",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Warlords Of Draenor",
		drop_rate = "0",
		id = "33",
	},
	34 = {
		name = "Primal Gladiator's Longbow",
		location = "Warspear",
		source = "Blood Guard Axelash",
		territory = "Alliance",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "34",
	},
	35 = {
		name = "Crystalline Branch of the Brackenspore",
		location = "Highmaul",
		source = "Brackenspore",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Warlords Of Draenor",
		drop_rate = "12.71",
		id = "35",
	},
	36 = {
		name = "Wall-Watcher's Longbow",
		location = "Lunarfall",
		source = "Annihilon",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "4.47",
		id = "36",
	},
	37 = {
		name = "Primal Gladiator's Longbow",
		location = "Stormshield",
		source = "Ingrid Blackingot",
		territory = "War Zone",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "37",
	},
	38 = {
		name = "Wild Combatant's Longbow",
		location = "Stormshield",
		source = "Slugg Spinbolt",
		territory = "War Zone",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "38",
	},
	39 = {
		name = "Wild Combatant's Longbow",
		location = "Warspear",
		source = "Fobbly Kickfix",
		territory = "Alliance",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "39",
	},
	40 = {
		name = "Shield-Shatter Longbow",
		location = "Highmaul",
		source = "Koragh",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Warlords Of Draenor",
		drop_rate = "0",
		id = "40",
	},
	41 = {
		name = "Bonetooth Longbow",
		location = "Shadowmoon Burial Grounds",
		source = "Bonemaw",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Warlords Of Draenor",
		drop_rate = "13.77",
		id = "41",
	},
	42 = {
		name = "Talon Guard Bow",
		location = "Spires of Arak",
		source = "When All Is Aligned",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "42",
	},
	43 = {
		name = "Mighty Gorian Hunting Bow",
		location = "Nagrand",
		source = "Reglakks Research",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "43",
	},
	44 = {
		name = "Primal Combatant's Longbow",
		location = "Warspear",
		source = "Stone Guard Brokefist",
		territory = "Alliance",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "44",
	},
	45 = {
		name = "Gorestrung Longbow of Kel'tann",
		location = "Tanaan Jungle",
		source = "Blackfang Prowler",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.01",
		id = "45",
	},
	46 = {
		name = "Bal'ra's Compound Bow",
		location = "Gorgrond",
		source = "Hunter Balra",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "39.45",
		id = "46",
	},
	47 = {
		name = "Primal Combatant's Longbow",
		location = "Stormshield",
		source = "Bregg Coppercast",
		territory = "War Zone",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "Unknown",
		id = "47",
	},
	48 = {
		name = "Howling Bow",
		location = "Nagrand",
		source = "Bloodied Slayer",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.05",
		id = "48",
	},
	49 = {
		name = "Gorian Bow",
		location = "Tanaan Jungle",
		source = "Felborn Enforcer",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.03",
		id = "49",
	},
	50 = {
		name = "Admiral Taylor's Hunting Bow",
		location = "Spires of Arak",
		source = "Admiral Taylor",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "50",
	},
	51 = {
		name = "Longclaw Bow",
		location = "Nagrand",
		source = "Tamed Clefthoof",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.03",
		id = "51",
	},
	52 = {
		name = "Bloodmane Bow",
		location = "Nagrand",
		source = "Tamed Clefthoof",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.03",
		id = "52",
	},
	53 = {
		name = "Prideful Gladiator's Longbow",
		location = "Valley of the Four Winds",
		source = "Starlight Sinclair",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "53",
	},
	54 = {
		name = "Prideful Gladiator's Longbow",
		location = "Kun-Lai Summit",
		source = "Shonn Su",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "54",
	},
	55 = {
		name = "Skettis Bow",
		location = "Auchindoun",
		source = "Felguard",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.11",
		id = "55",
	},
	56 = {
		name = "Shattered Tortoiseshell Longbow",
		location = "Throne of Thunder",
		source = "Tortos",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "9.89",
		id = "56",
	},
	57 = {
		name = "Miracoran, the Vehement Chord",
		location = "Throne of Thunder",
		source = "Lulin",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "57",
	},
	58 = {
		name = "Shattered Tortoiseshell Longbow",
		location = "Throne of Thunder",
		source = "Tortos",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "2.88",
		id = "58",
	},
	59 = {
		name = "Miracoran, the Vehement Chord",
		location = "Throne of Thunder",
		source = "Lulin",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "59",
	},
	60 = {
		name = "Dagryn's Discarded Longbow",
		location = "Siege of Orgrimmar",
		source = "Galakras",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "11.69",
		id = "60",
	},
	61 = {
		name = "Hisek's Reserve Longbow",
		location = "Siege of Orgrimmar",
		source = "Skeer the Bloodseeker",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "61",
	},
	62 = {
		name = "Abandoned Dark Iron Longbow",
		location = "Gorgrond",
		source = "Down the Goren Hole",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "62",
	},
	63 = {
		name = "Auchenai Bow",
		location = "Iron Docks",
		source = "Gromkar Technician",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.45",
		id = "63",
	},
	64 = {
		name = "Ogron Slayer's Eye-Poker",
		location = "Gorgrond",
		source = "Fair Warning",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "64",
	},
	65 = {
		name = "Shattered Tortoiseshell Longbow",
		location = "Throne of Thunder",
		source = "Tortos",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.31",
		id = "65",
	},
	66 = {
		name = "Miracoran, the Vehement Chord",
		location = "Throne of Thunder",
		source = "Lei Shen",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "66",
	},
	67 = {
		name = "Incised Bow",
		location = "Gorgrond",
		source = "Steamscar Warrior",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.09",
		id = "67",
	},
	68 = {
		name = "Shattered Tortoiseshell Longbow",
		location = "Throne of Thunder",
		source = "Tortos",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "4.42",
		id = "68",
	},
	69 = {
		name = "Miracoran, the Vehement Chord",
		location = "Throne of Thunder",
		source = "Lulin",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "69",
	},
	70 = {
		name = "Grievous Gladiator's Longbow",
		location = "Kun-Lai Summit",
		source = "Acon Deathwielder",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "70",
	},
	71 = {
		name = "Grievous Gladiator's Longbow",
		location = "Valley of the Four Winds",
		source = "Ethan Natice",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "71",
	},
	72 = {
		name = "Bow of the Iron Wolf",
		location = "Frostfire Ridge",
		source = "The Iron Wolf",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "72",
	},
	73 = {
		name = "Rangari Initiate Longbow",
		location = "Shadowmoon Valley",
		source = "Darkness Falls",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "quest",
		id = "73",
	},
	74 = {
		name = "Creeperclaw Bow",
		location = "Gorgrond",
		source = "Lesser Brimfury",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.08",
		id = "74",
	},
	75 = {
		name = "Fang Kung, Spark of Titans",
		location = "Mogu'shan Vaults",
		source = "Jan-xi",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "5.97",
		id = "75",
	},
	76 = {
		name = "Shattered Tortoiseshell Longbow",
		location = "Throne of Thunder",
		source = "Tortos",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "6.98",
		id = "76",
	},
	77 = {
		name = "Miracoran, the Vehement Chord",
		location = "Throne of Thunder",
		source = "Tortos",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "77",
	},
	78 = {
		name = "Vinewrapped Bow",
		location = "Gorgrond",
		source = "Bloom Weaver",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.05",
		id = "78",
	},
	79 = {
		name = "Fang Kung, Spark of Titans",
		location = "Mogu'shan Vaults",
		source = "Qin-xi",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.75",
		id = "79",
	},
	80 = {
		name = "Fang Kung, Spark of Titans",
		location = "Mogu'shan Vaults",
		source = "Jan-xi",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "80",
	},
	81 = {
		name = "Klatith, Fangs of the Swarm",
		location = "Gate of the Setting Sun",
		source = "Raigonn",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.43",
		id = "81",
	},
	82 = {
		name = "Malevolent Gladiator's Longbow",
		location = "Kun-Lai Summit",
		source = "Doris Chiltonius",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "82",
	},
	83 = {
		name = "Mogu Sportsman's Bow",
		location = "Isle of Thunder",
		source = "Ancient Mogu Guardian",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "18.54",
		id = "83",
	},
	84 = {
		name = "Featherdraw Longbow",
		location = "Timeless Isle",
		source = "Mistweaver Ai",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "Unknown",
		id = "84",
	},
	85 = {
		name = "Klatith, Fangs of the Swarm",
		location = "Gate of the Setting Sun",
		source = "Raigonn",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Mists Of Pandaria",
		drop_rate = "0",
		id = "85",
	},
	86 = {
		name = "Tempestuous Longbow",
		location = "Siege of Niuzao Temple",
		source = "General Pavalak",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Mists Of Pandaria",
		drop_rate = "17.21",
		id = "86",
	},
	87 = {
		name = "Ennadee's Twirling Longbow",
		location = "Siege of Orgrimmar",
		source = "Lingering Corruption",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.01",
		id = "87",
	},
	88 = {
		name = "Tempestuous Longbow",
		location = "Siege of Niuzao Temple",
		source = "General Pavalak",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Mists Of Pandaria",
		drop_rate = "12.76",
		id = "88",
	},
	89 = {
		name = "Tempestuous Longbow",
		location = "Siege of Niuzao Temple",
		source = "General Pavalak",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.86",
		id = "89",
	},
	90 = {
		name = "Bow of the Rikkitun",
		location = "Dread Wastes",
		source = "The Horror Comes A-Rising",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "quest",
		id = "90",
	},
	91 = {
		name = "Frostbitten Bow",
		location = "Frostfire Ridge",
		source = "Grimfrost Drudge",
		territory = "Horde",
		category_territory = "",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.07",
		id = "91",
	},
	92 = {
		name = "Lunarglow Bow",
		location = "Bloodmaul Slag Mines",
		source = "Bloodmaul Slaver",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Warlords Of Draenor",
		drop_rate = "0.29",
		id = "92",
	},
	93 = {
		name = "Engraved Bow",
		location = "Mogu'shan Palace",
		source = "Kargesh Ribcrusher",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.0",
		id = "93",
	},
	94 = {
		name = "Shado-Pan Ranger's Bow",
		location = "Townlong Steppes",
		source = "Last Toll of the Yaungol",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "quest",
		id = "94",
	},
	95 = {
		name = "Restrung Voodoo Bow",
		location = "Isle of Giants",
		source = "Zandalari Dinomancer",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.19",
		id = "95",
	},
	96 = {
		name = "Rigid Bow",
		location = "Kun-Lai Summit",
		source = "Highlands Mushan",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.12",
		id = "96",
	},
	97 = {
		name = "Inlaid Bow",
		location = "Siege of Orgrimmar",
		source = "Korkron Grunt",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.02",
		id = "97",
	},
	98 = {
		name = "Marista Bow",
		location = "Krasarang Wilds",
		source = "Balance",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "quest",
		id = "98",
	},
	99 = {
		name = "Barbarian Bow",
		location = "Kun-Lai Summit",
		source = "Ordo Overseer",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.25",
		id = "99",
	},
	100 = {
		name = "Cataclysmic Gladiator's Longbow",
		location = "Orgrimmar",
		source = "Sergeant Thunderhorn",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "100",
	},
	101 = {
		name = "Themios the Darkbringer",
		location = "Blackwing Descent",
		source = "Atramedes",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Cataclysm",
		drop_rate = "12.7",
		id = "101",
	},
	102 = {
		name = "Vicious Gladiator's Longbow",
		location = "Tanaris",
		source = "Blazzek the Biter",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "102",
	},
	103 = {
		name = "Themios the Darkbringer",
		location = "Blackwing Descent",
		source = "Atramedes",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Cataclysm",
		drop_rate = "13.42",
		id = "103",
	},
	104 = {
		name = "Voodoo Hunting Bow",
		location = "Zul'Aman",
		source = "The Hex Lords Fetish",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "104",
	},
	105 = {
		name = "Mandokir's Tribute",
		location = "Zul'Gurub",
		source = "Jindo the Godbreaker",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "13.78",
		id = "105",
	},
	106 = {
		name = "Ruthless Gladiator's Longbow",
		location = "Orgrimmar",
		source = "Blood Guard Zarshi",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "106",
	},
	107 = {
		name = "Windrunner's Bow",
		location = "End Time",
		source = "Echo of Sylvanas",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "14.04",
		id = "107",
	},
	108 = {
		name = "Ironfeather Longbow",
		location = "Well of Eternity",
		source = "The Path to the Dragon Soul",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "108",
	},
	109 = {
		name = "Amber Messenger",
		location = "Blackrock Caverns",
		source = "Ascendant Lord Obsidius",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "8.02",
		id = "109",
	},
	110 = {
		name = "Overpowered Chicken Splitter",
		location = "Dalaran",
		source = "Timofey Oshenko",
		territory = "",
		category_territory = "",
		expansion = "Legion",
		drop_rate = "Unknown",
		id = "110",
	},
	111 = {
		name = "Ravenheart Longbow",
		location = "The Stonecore",
		source = "Stonecore Rift Conjurer",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.0",
		id = "111",
	},
	112 = {
		name = "Windrunner's Bow",
		location = "End Time",
		source = "Echo of Sylvanas",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "1.7",
		id = "112",
	},
	113 = {
		name = "Polished Bow",
		location = "The Jade Forest",
		source = "Garroshar Grunt",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.09",
		id = "113",
	},
	114 = {
		name = "Bronzed Bow",
		location = "Valley of the Four Winds",
		source = "Kunzen Collector",
		territory = "Horde",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "0.02",
		id = "114",
	},
	115 = {
		name = "Sporeshot",
		location = "Deepholm",
		source = "Wrath of the Fungalmancer",
		territory = "Horde",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "115",
	},
	116 = {
		name = "Irontree Bow",
		location = "The Stonecore",
		source = "Stonecore Flayer",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.0",
		id = "116",
	},
	117 = {
		name = "Arrowspike Longbow",
		location = "Uldum",
		source = "Fortune and Glory",
		territory = "Horde",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "117",
	},
	118 = {
		name = "Amber Messenger",
		location = "Blackrock Caverns",
		source = "Ascendant Lord Obsidius",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "24.0",
		id = "118",
	},
	119 = {
		name = "Splinterspear Bow",
		location = "Deepholm",
		source = "Stone Drake",
		territory = "Horde",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "0.01",
		id = "119",
	},
	120 = {
		name = "Mardenholde Bow",
		location = "Tol Barad",
		source = "Alliance Mage Infantry",
		territory = "",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "0.0",
		id = "120",
	},
	121 = {
		name = "Bladefist Bow",
		location = "Blackrock Caverns",
		source = "Twilight Sadist",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.0",
		id = "121",
	},
	122 = {
		name = "Nethergarde Bow",
		location = "The Stonecore",
		source = "Stonecore Flayer",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.01",
		id = "122",
	},
	123 = {
		name = "Zod's Repeating Longbow",
		location = "Icecrown Citadel",
		source = "Lady Deathwhisper",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "25.07",
		id = "123",
	},
	124 = {
		name = "Steelspark Bow",
		location = "Blackrock Caverns",
		source = "Twilight Zealot",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.01",
		id = "124",
	},
	125 = {
		name = "Angerfang Bow",
		location = "Blackrock Caverns",
		source = "Twilight Zealot",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.01",
		id = "125",
	},
	126 = {
		name = "Razorwind Bow",
		location = "Blackrock Caverns",
		source = "Twilight Zealot",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Cataclysm",
		drop_rate = "0.01",
		id = "126",
	},
	127 = {
		name = "Breathstone-Infused Longbow",
		location = "Kelp'thar Forest",
		source = "Decompression",
		territory = "Horde",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "127",
	},
	128 = {
		name = "Breathstone-Infused Longbow",
		location = "Kelp'thar Forest",
		source = "Decompression",
		territory = "Horde",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "128",
	},
	129 = {
		name = "Accursed Bow of the Elite",
		location = "Naxxramas",
		source = "Gluth",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "6.14",
		id = "129",
	},
	130 = {
		name = "Arrowsong",
		location = "Naxxramas",
		source = "Gluth",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "2.0",
		id = "130",
	},
	131 = {
		name = "Deadly Gladiator's Longbow",
		location = "Dalaran",
		source = "Herwin Steampop",
		territory = "",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "131",
	},
	132 = {
		name = "Furious Gladiator's Longbow",
		location = "Dalaran",
		source = "Kylo Kelwin",
		territory = "",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "132",
	},
	133 = {
		name = "Relentless Gladiator's Longbow",
		location = "Dalaran",
		source = "Zom Bocom",
		territory = "",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "133",
	},
	134 = {
		name = "Siren's Cry",
		location = "Ulduar",
		source = "Auriaya",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "16.09",
		id = "134",
	},
	135 = {
		name = "Golemheart Longbow",
		location = "Ulduar",
		source = "Faceless Horror",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.31",
		id = "135",
	},
	136 = {
		name = "Zod's Repeating Longbow",
		location = "Icecrown Citadel",
		source = "Lady Deathwhisper",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "23.66",
		id = "136",
	},
	137 = {
		name = "Njorndar Bone Bow",
		location = "Icecrown Citadel",
		source = "Lady Deathwhisper",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "20.86",
		id = "137",
	},
	138 = {
		name = "Wrathful Gladiator's Longbow",
		location = "Dalaran",
		source = "Xazi Smolderpipe",
		territory = "",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "138",
	},
	139 = {
		name = "Njorndar Bone Bow",
		location = "Icecrown Citadel",
		source = "Lady Deathwhisper",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "18.47",
		id = "139",
	},
	140 = {
		name = "Siren's Cry",
		location = "Ulduar",
		source = "Auriaya",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "140",
	},
	141 = {
		name = "Drakkari Hunting Bow",
		location = "Gundrak",
		source = "Drakkari Colossus",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "141",
	},
	142 = {
		name = "Trophy Gatherer",
		location = "Utgarde Pinnacle",
		source = "Gortok Palehoof",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "7.04",
		id = "142",
	},
	143 = {
		name = "Titanium Compound Bow",
		location = "Ahn'kahet: The Old Kingdom",
		source = "Herald Volazj",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "3.65",
		id = "143",
	},
	144 = {
		name = "Trophy Gatherer",
		location = "Utgarde Pinnacle",
		source = "Gortok Palehoof",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "1.14",
		id = "144",
	},
	145 = {
		name = "Drakkari Hunting Bow",
		location = "Gundrak",
		source = "Drakkari Colossus",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "145",
	},
	146 = {
		name = "Titanium Compound Bow",
		location = "Ahn'kahet: The Old Kingdom",
		source = "Herald Volazj",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "2.48",
		id = "146",
	},
	147 = {
		name = "Massive Recurved Bow",
		location = "Icecrown Citadel",
		source = "Frostwing Whelp",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.01",
		id = "147",
	},
	148 = {
		name = "Military Compound Bow",
		location = "Halls of Lightning",
		source = "Hardened Steel Skycaller",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.39",
		id = "148",
	},
	149 = {
		name = "Shrieking Bow",
		location = "Icecrown Citadel",
		source = "Frostwing Whelp",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.0",
		id = "149",
	},
	150 = {
		name = "Bow of Regression",
		location = "Icecrown",
		source = "Retest Now",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "150",
	},
	151 = {
		name = "Wyrmstalker's Bow",
		location = "Icecrown",
		source = "Cradle of the Frostbrood",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "151",
	},
	152 = {
		name = "Bow of Bone and Sinew",
		location = "Icecrown",
		source = "Crush Dem Vrykuls!",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "152",
	},
	153 = {
		name = "Harnessed Longbow",
		location = "Icecrown Citadel",
		source = "Vengeful Fleshreaper",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.02",
		id = "153",
	},
	154 = {
		name = "Sin'dorei Recurve Bow",
		location = "Howling Fjord",
		source = "Sebastian Crane",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "154",
	},
	155 = {
		name = "Acute Shortbow",
		location = "Halls of Stone",
		source = "Dark Rune Warrior",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.01",
		id = "155",
	},
	156 = {
		name = "Roc-Feather Longbow",
		location = "Gundrak",
		source = "Spitting Cobra",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.01",
		id = "156",
	},
	157 = {
		name = "Dragon Slayer's Shortbow",
		location = "Sholazar Basin",
		source = "Post-partum Aggression",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "157",
	},
	158 = {
		name = "Advanced Flatbow",
		location = "Gundrak",
		source = "Drakkari Inciter",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.07",
		id = "158",
	},
	159 = {
		name = "Tracking Bow",
		location = "Halls of Stone",
		source = "Dark Rune Warrior",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.04",
		id = "159",
	},
	160 = {
		name = "High-Strung Bow",
		location = "Zul'Drak",
		source = "Stocking the Shelves",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "160",
	},
	161 = {
		name = "Golden Bow of Quel'Thalas",
		location = "Sunwell Plateau",
		source = "Lady Sacrolash",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "19.98",
		id = "161",
	},
	162 = {
		name = "Brutal Gladiator's Longbow",
		location = "Netherstorm",
		source = "Blaze Magmaburn",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "Unknown",
		id = "162",
	},
	163 = {
		name = "Astral Light Bow",
		location = "The Violet Hold",
		source = "Azure Sorceror",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.01",
		id = "163",
	},
	164 = {
		name = "Bristleblitz Striker",
		location = "Hyjal Summit",
		source = "Archimonde",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "17.8",
		id = "164",
	},
	165 = {
		name = "Black Bow of the Betrayer",
		location = "Black Temple",
		source = "Illidan Stormrage",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "19.16",
		id = "165",
	},
	166 = {
		name = "Black Bow of the Betrayer",
		location = "Black Temple",
		source = "Illidan Stormrage",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "Unknown",
		id = "166",
	},
	167 = {
		name = "Twisted Longbow",
		location = "Ahn'kahet: The Old Kingdom",
		source = "Plundering Geist",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.01",
		id = "167",
	},
	168 = {
		name = "Vengeful Gladiator's Longbow",
		location = "Netherstorm",
		source = "Kitzie Crankshot",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "Unknown",
		id = "168",
	},
	169 = {
		name = "Longbow of the Ruby Rider",
		location = "Dragonblight",
		source = "Wanton Warlord",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "169",
	},
	170 = {
		name = "Serpent Spine Longbow",
		location = "Serpentshrine Cavern",
		source = "Lady Vashj",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "14.99",
		id = "170",
	},
	171 = {
		name = "Dutiful Longbow",
		location = "The Nexus",
		source = "Crazed Mana-Surge",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.01",
		id = "171",
	},
	172 = {
		name = "Coldspike Longbow",
		location = "Howling Fjord",
		source = "Trail of Fire",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "172",
	},
	173 = {
		name = "Expert's Longbow",
		location = "Utgarde Keep",
		source = "Dragonflayer Metalworker",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.02",
		id = "173",
	},
	174 = {
		name = "Taut Driftwood Bow",
		location = "Borean Tundra",
		source = "Defeat the Gearmaster",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "174",
	},
	175 = {
		name = "Valiance Longbow",
		location = "Borean Tundra",
		source = "The Siege",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "quest",
		id = "175",
	},
	176 = {
		name = "Sunfury Bow of the Phoenix",
		location = "Karazhan",
		source = "Prince Malchezaar",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "0",
		id = "176",
	},
	177 = {
		name = "Starbolt Longbow",
		location = "Mana-Tombs",
		source = "Pandemonius",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "5.9",
		id = "177",
	},
	178 = {
		name = "Valanos' Longbow",
		location = "The Mechanar",
		source = "Gatewatcher Gyro-Kill",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.17",
		id = "178",
	},
	179 = {
		name = "Starbolt Longbow",
		location = "Mana-Tombs",
		source = "Pandemonius",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "2.16",
		id = "179",
	},
	180 = {
		name = "Dream Catcher Bow",
		location = "Serpentshrine Cavern",
		source = "Coilfang Serpentguard",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "0.07",
		id = "180",
	},
	181 = {
		name = "Windspear Longbow",
		location = "Blade's Edge Mountains",
		source = "Galvanoth",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "7.71",
		id = "181",
	},
	182 = {
		name = "Honorable Longbow",
		location = "Utgarde Keep",
		source = "Dragonflayer Ironhelm",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.03",
		id = "182",
	},
	183 = {
		name = "Yew Bow",
		location = "Borean Tundra",
		source = "Northsea Mercenary",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "0.1",
		id = "183",
	},
	184 = {
		name = "Orc Flatbow",
		location = "Black Temple",
		source = "Coilskar General",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "0.15",
		id = "184",
	},
	185 = {
		name = "Skyfire Hawk-Bow",
		location = "The Shattered Halls",
		source = "Warbringer Omrogg",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "12.81",
		id = "185",
	},
	186 = {
		name = "Melmorta's Twilight Longbow",
		location = "The Black Morass",
		source = "Chrono Lord Deja",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "10.31",
		id = "186",
	},
	187 = {
		name = "Skyfire Hawk-Bow",
		location = "The Shattered Halls",
		source = "Warbringer Omrogg",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "2.05",
		id = "187",
	},
	188 = {
		name = "Melmorta's Twilight Longbow",
		location = "The Black Morass",
		source = "Chrono Lord Deja",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "1.15",
		id = "188",
	},
	189 = {
		name = "Rocslayer Longbow",
		location = "Black Temple",
		source = "Temple Concubine",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "0.01",
		id = "189",
	},
	190 = {
		name = "Ranger's Recurved Bow",
		location = "Karazhan",
		source = "Spectral Servant",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "The Burning Crusade",
		drop_rate = "0.01",
		id = "190",
	},
	191 = {
		name = "Alley's Recurve",
		location = "Netherstorm",
		source = "Mark V is Alive!",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "quest",
		id = "191",
	},
	192 = {
		name = "Scorch Wood Bow",
		location = "Blade's Edge Mountains",
		source = "From the Ashes",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "quest",
		id = "192",
	},
	193 = {
		name = "Wrathtide Longbow",
		location = "The Steamvault",
		source = "Warlord Kalithresh",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "7.96",
		id = "193",
	},
	194 = {
		name = "Talbuk Hunting Bow",
		location = "Netherstorm",
		source = "Shaleskin Flayer",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "0.07",
		id = "194",
	},
	195 = {
		name = "Expert's Bow",
		location = "The Mechanar",
		source = "Bloodwarder Physician",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.02",
		id = "195",
	},
	196 = {
		name = "Marksman's Bow",
		location = "Hellfire Peninsula",
		source = "Quartermaster Urgronn",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "Unknown",
		id = "196",
	},
	197 = {
		name = "Thalassian Compound Bow",
		location = "The Underbog",
		source = "Underbog Lurker",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.01",
		id = "197",
	},
	198 = {
		name = "Ethereal Warp-Bow",
		location = "Mana-Tombs",
		source = "Nexus-Prince Shaffar",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "6.86",
		id = "198",
	},
	199 = {
		name = "Ethereal Warp-Bow",
		location = "Mana-Tombs",
		source = "Nexus-Prince Shaffar",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "1.0",
		id = "199",
	},
	200 = {
		name = "Razorsong Bow",
		location = "Mana-Tombs",
		source = "Ethereal Theurgist",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.04",
		id = "200",
	},
	201 = {
		name = "Viper Bow",
		location = "Mana-Tombs",
		source = "Ethereal Crypt Raider",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.01",
		id = "201",
	},
	202 = {
		name = "Mag'har Bow",
		location = "Hellfire Peninsula",
		source = "Administering the Salve",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "quest",
		id = "202",
	},
	203 = {
		name = "Warden's Longbow",
		location = "Zangarmarsh",
		source = "Escape from Umbrafen",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "quest",
		id = "203",
	},
	204 = {
		name = "Splintermark",
		location = "Zangarmarsh",
		source = "Horde Field Scout",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "Unknown",
		id = "204",
	},
	205 = {
		name = "Splintermark",
		location = "Zangarmarsh",
		source = "Alliance Field Scout",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "Unknown",
		id = "205",
	},
	206 = {
		name = "Windtalker Bow",
		location = "The Underbog",
		source = "Murkblood Oracle",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.24",
		id = "206",
	},
	207 = {
		name = "Telaari Longbow",
		location = "Hellfire Ramparts",
		source = "Bonechewer Destroyer",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.02",
		id = "207",
	},
	208 = {
		name = "Ashenvale Longbow",
		location = "Hellfire Ramparts",
		source = "Bleeding Hollow Darkcaster",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "The Burning Crusade",
		drop_rate = "0.02",
		id = "208",
	},
	209 = {
		name = "Brunnhildar Bow",
		location = "The Storm Peaks",
		source = "Warsmith Sigfinna",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "209",
	},
	210 = {
		name = "Azerothian Longbow",
		location = "Hellfire Peninsula",
		source = "Netherhound",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "0.06",
		id = "210",
	},
	211 = {
		name = "Striker's Mark",
		location = "Molten Core",
		source = "Magmadar",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "18.55",
		id = "211",
	},
	212 = {
		name = "Heartstriker",
		location = "Blackwing Lair",
		source = "Broodlord Lashlayer",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "11.38",
		id = "212",
	},
	213 = {
		name = "Bow of Taut Sinew",
		location = "Ruins of Ahn'Qiraj",
		source = "Ayamiss the Hunter",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "0",
		id = "213",
	},
	214 = {
		name = "Huhuran's Stinger",
		location = "Temple of Ahn'Qiraj",
		source = "Princess Huhuran",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "9.43",
		id = "214",
	},
	215 = {
		name = "Riphook",
		location = "Blackrock Spire",
		source = "Shadow Hunter Voshgajin",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "14.95",
		id = "215",
	},
	216 = {
		name = "Eaglehorn Long Bow",
		location = "Ruins of Ahn'Qiraj",
		source = "Captain Tuubid",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "0.19",
		id = "216",
	},
	217 = {
		name = "Outrider's Bow",
		location = "Northern Barrens",
		source = "Kelm Hargunth",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "217",
	},
	218 = {
		name = "Outrunner's Bow",
		location = "Ashenvale",
		source = "Illiyana Moonblaze",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "218",
	},
	219 = {
		name = "Blasthorn Bow",
		location = "Temple of Ahn'Qiraj",
		source = "Vekniss Guardian",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "0.07",
		id = "219",
	},
	220 = {
		name = "Archstrike Bow",
		location = "Blackwing Lair",
		source = "Nefarian",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "2.1",
		id = "220",
	},
	221 = {
		name = "Hawkeye Bow",
		location = "Molten Core",
		source = "Molten Destroyer",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "0.13",
		id = "221",
	},
	222 = {
		name = "Stout Oak Longbow",
		location = "Terokkar Forest",
		source = "Thinning the Ranks",
		territory = "Horde",
		category_territory = "",
		expansion = "The Burning Crusade",
		drop_rate = "quest",
		id = "222",
	},
	223 = {
		name = "Sandstrider's Mark",
		location = "Silithus",
		source = "Wanted - Deathclasp, Terror of the Sands",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "223",
	},
	224 = {
		name = "Stinging Bow",
		location = "Sunken Temple",
		source = "Atalai Deathwalker",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.01",
		id = "224",
	},
	225 = {
		name = "Gryphonwing Long Bow",
		location = "Ruins of Ahn'Qiraj",
		source = "Silicate Feeder",
		territory = "Horde",
		category_territory = "Raid",
		expansion = "",
		drop_rate = "0.06",
		id = "225",
	},
	226 = {
		name = "Quillfire Bow",
		location = "Sunken Temple",
		source = "Hazzas",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.25",
		id = "226",
	},
	227 = {
		name = "Hurricane",
		location = "Blackrock Depths",
		source = "Shadowforge Senator",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.01",
		id = "227",
	},
	228 = {
		name = "Screeching Bow",
		location = "Stratholme",
		source = "Baroness Anastari",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "21.94",
		id = "228",
	},
	229 = {
		name = "Outrider's Bow",
		location = "Northern Barrens",
		source = "Kelm Hargunth",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "229",
	},
	230 = {
		name = "Outrunner's Bow",
		location = "Ashenvale",
		source = "Illiyana Moonblaze",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "230",
	},
	231 = {
		name = "Siege Bow",
		location = "Blackrock Depths",
		source = "BaelGar",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.29",
		id = "231",
	},
	232 = {
		name = "Morcott's Bow",
		location = "Winterspring",
		source = "Ursius",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "232",
	},
	233 = {
		name = "Houndmaster's Bow",
		location = "Blackrock Depths",
		source = "Houndmaster Grebmar",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "17.07",
		id = "233",
	},
	234 = {
		name = "Harpy Needler",
		location = "Stratholme",
		source = "Ramstein the Gorger",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "1.91",
		id = "234",
	},
	235 = {
		name = "Sylvan Shortbow",
		location = "Twilight Highlands",
		source = "Brian Terrel",
		territory = "Horde",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "Unknown",
		id = "235",
	},
	236 = {
		name = "Needle Threader",
		location = "Zul'Farrak",
		source = "Sandfury Blood Drinker",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.01",
		id = "236",
	},
	237 = {
		name = "Massive Longbow",
		location = "Howling Fjord",
		source = "Talu Frosthoof",
		territory = "Horde",
		category_territory = "",
		expansion = "Wrath Of The Lich King",
		drop_rate = "Unknown",
		id = "237",
	},
	238 = {
		name = "Moonbow",
		location = "Felwood",
		source = "The Inner Circle",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "238",
	},
	239 = {
		name = "Quillshooter",
		location = "Razorfen Downs",
		source = "Festering Spiderling",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.03",
		id = "239",
	},
	240 = {
		name = "Crusader Bow",
		location = "Dire Maul",
		source = "Ferra",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.19",
		id = "240",
	},
	241 = {
		name = "Outrider's Bow",
		location = "Northern Barrens",
		source = "Kelm Hargunth",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "241",
	},
	242 = {
		name = "Outrunner's Bow",
		location = "Ashenvale",
		source = "Illiyana Moonblaze",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "242",
	},
	243 = {
		name = "Bow of Searing Arrows",
		location = "Dire Maul",
		source = "Eldreth Darter",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "5.24",
		id = "243",
	},
	244 = {
		name = "Satyr's Bow",
		location = "Dire Maul",
		source = "Zevrim Thornhoof",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "20.48",
		id = "244",
	},
	245 = {
		name = "Warpwood Bow",
		location = "Dire Maul",
		source = "Alzzin the Wildshaper",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "quest",
		id = "245",
	},
	246 = {
		name = "Trueshot Bow",
		location = "Dire Maul",
		source = "Hydrospawn",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.13",
		id = "246",
	},
	247 = {
		name = "Baelog's Shortbow",
		location = "Uldaman",
		source = "Eric ",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "Unknown",
		id = "247",
	},
	248 = {
		name = "Monolithic Bow",
		location = "Uldaman",
		source = "Cleft Scorpid",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.02",
		id = "248",
	},
	249 = {
		name = "Skystriker Bow",
		location = "Feralas",
		source = "Ironfur Bear",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "0.07",
		id = "249",
	},
	250 = {
		name = "Seasoned Marshwood Bow",
		location = "Dustwallow Marsh",
		source = "The Reagent Thief",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "250",
	},
	251 = {
		name = "Shadowleaf Bow",
		location = "Feralas",
		source = "Might of the Sentinels",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "251",
	},
	252 = {
		name = "Stonemaul Slinger",
		location = "Feralas",
		source = "Might of the Stonemaul",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "252",
	},
	253 = {
		name = "Nightstalker Bow",
		location = "Razorfen Kraul",
		source = "Groyat, the Blind Hunter",
		territory = "Alliance",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "18.96",
		id = "253",
	},
	254 = {
		name = "Dense Shortbow",
		location = "Arathi Highlands",
		source = "Muuta",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "254",
	},
	255 = {
		name = "Long Redwood Bow",
		location = "Razorfen Kraul",
		source = "Warlord Ramtusk",
		territory = "Alliance",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.16",
		id = "255",
	},
	256 = {
		name = "Whipwood Recurve Bow",
		location = "Maraudon",
		source = "Creeping Sludge",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.25",
		id = "256",
	},
	257 = {
		name = "Outrider's Bow",
		location = "Northern Barrens",
		source = "Kelm Hargunth",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "257",
	},
	258 = {
		name = "Outrunner's Bow",
		location = "Ashenvale",
		source = "Illiyana Moonblaze",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "258",
	},
	259 = {
		name = "Harpyclaw Short Bow",
		location = "Razorfen Kraul",
		source = "Enormous Bullfrog",
		territory = "Alliance",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "5.24",
		id = "259",
	},
	260 = {
		name = "Spinescale Longbow",
		location = "Desolace",
		source = "Return and Report",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "260",
	},
	261 = {
		name = "Ravenwood Bow",
		location = "Duskwood",
		source = "Fenros",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "0.51",
		id = "261",
	},
	262 = {
		name = "Sturdy Recurve",
		location = "Ironforge",
		source = "Skolmin Goldfury",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "262",
	},
	263 = {
		name = "Archer's Longbow",
		location = "Razorfen Kraul",
		source = "Hunter Bonetusk",
		territory = "Alliance",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.21",
		id = "263",
	},
	264 = {
		name = "Bow of Invisible Aim",
		location = "Stonetalon Mountains",
		source = "Spy Infestation",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "264",
	},
	265 = {
		name = "Long Battle Bow",
		location = "Gnomeregan",
		source = "Grubbis",
		territory = "War Zone",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.29",
		id = "265",
	},
	266 = {
		name = "Precision Bow",
		location = "Hillsbrad Foothills",
		source = "Mudsnout Gnoll",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "0.01",
		id = "266",
	},
	267 = {
		name = "Silent Huntress",
		location = "Arathi Highlands",
		source = "The Real Threat",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "267",
	},
	268 = {
		name = "Ranger Bow",
		location = "The Stockade",
		source = "Searing Destroyer",
		territory = "War Zone",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.77",
		id = "268",
	},
	269 = {
		name = "Naga Heartpiercer",
		location = "Blackfathom Deeps",
		source = "Domina",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "25.06",
		id = "269",
	},
	270 = {
		name = "Outrider's Bow",
		location = "Northern Barrens",
		source = "Kelm Hargunth",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "270",
	},
	271 = {
		name = "Outrunner's Bow",
		location = "Ashenvale",
		source = "Illiyana Moonblaze",
		territory = "Horde",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "271",
	},
	272 = {
		name = "Short Ash Bow",
		location = "Blackfathom Deeps",
		source = "Subjugator Korul",
		territory = "Horde",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.13",
		id = "272",
	},
	273 = {
		name = "Old Guard's Bow",
		location = "Wetlands",
		source = "Yorla Darksnare",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "273",
	},
	274 = {
		name = "Venomstrike",
		location = "Wailing Caverns",
		source = "Lord Serpentis",
		territory = "Alliance",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "18.91",
		id = "274",
	},
	275 = {
		name = "Farstrider's Longbow",
		location = "Ghostlands",
		source = "The Traitors Destruction",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "275",
	},
	276 = {
		name = "Light Bow",
		location = "Wetlands",
		source = "Bluegill Oracle",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "0.02",
		id = "276",
	},
	277 = {
		name = "Well Crafted Long Bow",
		location = "Ghostlands",
		source = "Bring Me Kelgashs Head!",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "277",
	},
	278 = {
		name = "Fine Longbow",
		location = "Broken Shore",
		source = "Uthrok",
		territory = "Horde",
		category_territory = "",
		expansion = "Legion",
		drop_rate = "Unknown",
		id = "278",
	},
	279 = {
		name = "Blackwood Hunter's Bow",
		location = "Darkshore",
		source = "The Defiler",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "279",
	},
	280 = {
		name = "Fine Shortbow",
		location = "Ironforge",
		source = "Skolmin Goldfury",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "Unknown",
		id = "280",
	},
	281 = {
		name = "Heavy Shortbow",
		location = "Ragefire Chasm",
		source = "Dark Shaman Koranthal",
		territory = "Alliance",
		category_territory = "Dungeon",
		expansion = "",
		drop_rate = "0.24",
		id = "281",
	},
	282 = {
		name = "Night Elven Bow",
		location = "Gilneas",
		source = "They Have Allies, But So Do We",
		territory = "War Zone",
		category_territory = "",
		expansion = "Cataclysm",
		drop_rate = "quest",
		id = "282",
	},
	283 = {
		name = "Darkshore Bow",
		location = "Darkshore",
		source = "Remembrance of Auberdine",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "283",
	},
	284 = {
		name = "Shipwreck Bow",
		location = "Darkshore",
		source = "An Ocean Not So Deep",
		territory = "War Zone",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "284",
	},
	285 = {
		name = "Hunting Bow",
		location = "Northern Barrens",
		source = "Sunscale Lashtail",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "0.08",
		id = "285",
	},
	286 = {
		name = "Quel'Thalas Recurve",
		location = "Ghostlands",
		source = "Goldenmist Village",
		territory = "Alliance",
		category_territory = "",
		expansion = "",
		drop_rate = "quest",
		id = "286",
	},
	287 = {
		name = "Darkspear Hunter's Bow",
		location = "Echo Isles",
		source = "Proving Pit",
		territory = "Alliance",
		category_territory = "",
		expansion = "Mists Of Pandaria",
		drop_rate = "quest",
		id = "287",
	},
	lol = "d"
}