cloth-chest_url_db = {
	0 = {
		source = "Kiatke",
		category_territory = "",
		name = "Lightwarper Vestments",
		territory = "War Zone",
		drop_rate = "Unknown",
		location = "Stormwind City",
		id = "0",
		expansion = "",
	},
	1 = {
		source = "Harthak Stormcaller",
		category_territory = "Dungeon",
		name = "Growing Robe",
		territory = "Horde",
		drop_rate = "0.23",
		location = "Mogu'shan Palace",
		id = "1",
		expansion = "Mists Of Pandaria",
	},
	2 = {
		source = "Alin the Finder",
		category_territory = "",
		name = "Mountainscaler Satin Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Townlong Steppes",
		id = "2",
		expansion = "Mists Of Pandaria",
	},
	3 = {
		source = "Alin the Finder",
		category_territory = "",
		name = "Mountainscaler Silk Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Townlong Steppes",
		id = "3",
		expansion = "Mists Of Pandaria",
	},
	4 = {
		source = "Morchok",
		category_territory = "Raid",
		name = "Robe of Glowing Stone",
		territory = "Horde",
		drop_rate = "12.18",
		location = "Dragon Soul",
		id = "4",
		expansion = "Cataclysm",
	},
	5 = {
		source = "JamusVaz",
		category_territory = "",
		name = "Robes of Dying Light",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "5",
		expansion = "",
	},
	6 = {
		source = "JamusVaz",
		category_territory = "",
		name = "Time Lord's Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "6",
		expansion = "",
	},
	7 = {
		source = "JamusVaz",
		category_territory = "",
		name = "Robes of the Faceless Shroud",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "7",
		expansion = "",
	},
	8 = {
		source = "JamusVaz",
		category_territory = "",
		name = "Robes of Dying Light",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "8",
		expansion = "",
	},
	9 = {
		source = "The Silkwood Road",
		category_territory = "",
		name = "Ambermist Robe",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Jade Forest",
		id = "9",
		expansion = "Mists Of Pandaria",
	},
	10 = {
		source = "The Silkwood Road",
		category_territory = "",
		name = "Silkwood Robe",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Jade Forest",
		id = "10",
		expansion = "Mists Of Pandaria",
	},
	11 = {
		source = "Tanithria",
		category_territory = "",
		name = "Windwool Tunic",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "11",
		expansion = "Legion",
	},
	12 = {
		source = "Onyxia",
		category_territory = "Raid",
		name = "Shadowblaze Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Blackwing Descent",
		id = "12",
		expansion = "Cataclysm",
	},
	13 = {
		source = "Drakonid Drudge",
		category_territory = "Raid",
		name = "Shadowforge's Lightbound Smock",
		territory = "Horde",
		drop_rate = "0.75",
		location = "Blackwing Descent",
		id = "13",
		expansion = "Cataclysm",
	},
	14 = {
		source = "Halfus Wyrmbreaker",
		category_territory = "Raid",
		name = "Robes of the Burning Acolyte",
		territory = "Horde",
		drop_rate = "9.0",
		location = "The Bastion of Twilight",
		id = "14",
		expansion = "Cataclysm",
	},
	15 = {
		source = "Rugok",
		category_territory = "",
		name = "Firelord's Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "15",
		expansion = "",
	},
	16 = {
		source = "Rugok",
		category_territory = "",
		name = "Shadowflame Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "16",
		expansion = "",
	},
	17 = {
		source = "Rugok",
		category_territory = "",
		name = "Mercurial Vestment",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "17",
		expansion = "",
	},
	18 = {
		source = "Rugok",
		category_territory = "",
		name = "Mercurial Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "18",
		expansion = "",
	},
	19 = {
		source = "Blazzek the Biter",
		category_territory = "",
		name = "Vicious Gladiator's Silk Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "19",
		expansion = "",
	},
	20 = {
		source = "Blazzek the Biter",
		category_territory = "",
		name = "Vicious Gladiator's Mooncloth Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "20",
		expansion = "",
	},
	21 = {
		source = "Blazzek the Biter",
		category_territory = "",
		name = "Vicious Gladiator's Satin Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "21",
		expansion = "",
	},
	22 = {
		source = "Blazzek the Biter",
		category_territory = "",
		name = "Vicious Gladiator's Felweave Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "22",
		expansion = "",
	},
	23 = {
		source = "Onyxia",
		category_territory = "Raid",
		name = "Shadowblaze Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Blackwing Descent",
		id = "23",
		expansion = "Cataclysm",
	},
	24 = {
		source = "Halfus Wyrmbreaker",
		category_territory = "Raid",
		name = "Robes of the Burning Acolyte",
		territory = "Horde",
		drop_rate = "10.54",
		location = "The Bastion of Twilight",
		id = "24",
		expansion = "Cataclysm",
	},
	25 = {
		source = "Rugok",
		category_territory = "",
		name = "Firelord's Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "25",
		expansion = "",
	},
	26 = {
		source = "Rugok",
		category_territory = "",
		name = "Mercurial Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "26",
		expansion = "",
	},
	27 = {
		source = "Rugok",
		category_territory = "",
		name = "Mercurial Vestment",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "27",
		expansion = "",
	},
	28 = {
		source = "Rugok",
		category_territory = "",
		name = "Shadowflame Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "28",
		expansion = "",
	},
	29 = {
		source = "Garr",
		category_territory = "",
		name = "Dizze's Whirling Robe",
		territory = "Horde",
		drop_rate = "6.1",
		location = "Mount Hyjal",
		id = "29",
		expansion = "Cataclysm",
	},
	30 = {
		source = "Daakara",
		category_territory = "Dungeon",
		name = "Hexing Robes",
		territory = "Horde",
		drop_rate = "14.71",
		location = "Zul'Aman",
		id = "30",
		expansion = "Cataclysm",
	},
	31 = {
		source = "Warlord of the Amani",
		category_territory = "Dungeon",
		name = "Robes of Dissention",
		territory = "Horde",
		drop_rate = "quest",
		location = "Zul'Aman",
		id = "31",
		expansion = "Cataclysm",
	},
	32 = {
		source = "Blood Guard Zarshi",
		category_territory = "",
		name = "Ruthless Gladiator's Silk Robe",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "32",
		expansion = "",
	},
	33 = {
		source = "Blood Guard Zarshi",
		category_territory = "",
		name = "Ruthless Gladiator's Mooncloth Robe",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "33",
		expansion = "",
	},
	34 = {
		source = "Blood Guard Zarshi",
		category_territory = "",
		name = "Ruthless Gladiator's Satin Robe",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "34",
		expansion = "",
	},
	35 = {
		source = "Blood Guard Zarshi",
		category_territory = "",
		name = "Ruthless Gladiator's Felweave Raiment",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "35",
		expansion = "",
	},
	36 = {
		source = "Bethtilac",
		category_territory = "Raid",
		name = "Robes of Smoldering Devastation",
		territory = "Horde",
		drop_rate = "9.36",
		location = "Firelands",
		id = "36",
		expansion = "Cataclysm",
	},
	37 = {
		source = "Gunra",
		category_territory = "",
		name = "Robes of the Cleansing Flame",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "37",
		expansion = "",
	},
	38 = {
		source = "Gunra",
		category_territory = "",
		name = "Vestment of the Cleansing Flame",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "38",
		expansion = "",
	},
	39 = {
		source = "Gunra",
		category_territory = "",
		name = "Balespider's Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "39",
		expansion = "",
	},
	40 = {
		source = "Gunra",
		category_territory = "",
		name = "Firehawk Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "40",
		expansion = "",
	},
	41 = {
		source = "Ecton Brasstumbler",
		category_territory = "",
		name = "Ruthless Gladiator's Silk Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "41",
		expansion = "",
	},
	42 = {
		source = "Ecton Brasstumbler",
		category_territory = "",
		name = "Ruthless Gladiator's Mooncloth Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "42",
		expansion = "",
	},
	43 = {
		source = "Ecton Brasstumbler",
		category_territory = "",
		name = "Ruthless Gladiator's Satin Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "43",
		expansion = "",
	},
	44 = {
		source = "Ecton Brasstumbler",
		category_territory = "",
		name = "Ruthless Gladiator's Felweave Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Tanaris",
		id = "44",
		expansion = "",
	},
	45 = {
		source = "Echo of Tyrande",
		category_territory = "Dungeon",
		name = "Whisperwind Robes",
		territory = "Horde",
		drop_rate = "11.8",
		location = "End Time",
		id = "45",
		expansion = "Cataclysm",
	},
	46 = {
		source = "Ammunae",
		category_territory = "Dungeon",
		name = "Robes of Rampant Growth",
		territory = "Horde",
		drop_rate = "19.85",
		location = "Halls of Origination",
		id = "46",
		expansion = "Cataclysm",
	},
	47 = {
		source = "Romogg Bonecrusher",
		category_territory = "Dungeon",
		name = "Inquisition Robes",
		territory = "Horde",
		drop_rate = "9.31",
		location = "Blackrock Caverns",
		id = "47",
		expansion = "Cataclysm",
	},
	48 = {
		source = "Ammunae",
		category_territory = "Dungeon",
		name = "Robes of Rampant Growth",
		territory = "Horde",
		drop_rate = "7.88",
		location = "Halls of Origination",
		id = "48",
		expansion = "Cataclysm",
	},
	49 = {
		source = "Anraphet",
		category_territory = "Dungeon",
		name = "Anraphet's Regalia",
		territory = "Horde",
		drop_rate = "15.52",
		location = "Halls of Origination",
		id = "49",
		expansion = "Cataclysm",
	},
	50 = {
		source = "Anraphet",
		category_territory = "Dungeon",
		name = "Anraphet's Regalia",
		territory = "Horde",
		drop_rate = "9.7",
		location = "Halls of Origination",
		id = "50",
		expansion = "Cataclysm",
	},
	51 = {
		source = "Rugok",
		category_territory = "",
		name = "Robes of Embalmed Darkness",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "51",
		expansion = "",
	},
	52 = {
		source = "Rugok",
		category_territory = "",
		name = "Musk Rose Robes",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "52",
		expansion = "",
	},
	53 = {
		source = "Blacksmith Abasi",
		category_territory = "",
		name = "Robes of Orsis",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Uldum",
		id = "53",
		expansion = "Cataclysm",
	},
	54 = {
		source = "Baron Ashbury",
		category_territory = "Dungeon",
		name = "Robes of Arugal",
		territory = "Alliance",
		drop_rate = "19.26",
		location = "Shadowfang Keep",
		id = "54",
		expansion = "",
	},
	55 = {
		source = "Skullcrusher the Mountain",
		category_territory = "",
		name = "Overly Intelligent Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Twilight Highlands",
		id = "55",
		expansion = "Cataclysm",
	},
	56 = {
		source = "Skullcrusher the Mountain",
		category_territory = "",
		name = "Overly Intelligent Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Twilight Highlands",
		id = "56",
		expansion = "Cataclysm",
	},
	57 = {
		source = "Rogoc",
		category_territory = "",
		name = "Bloodthirsty Gladiator's Felweave Raiment",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "57",
		expansion = "",
	},
	58 = {
		source = "Rogoc",
		category_territory = "",
		name = "Bloodthirsty Gladiator's Mooncloth Robe",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "58",
		expansion = "",
	},
	59 = {
		source = "Rogoc",
		category_territory = "",
		name = "Bloodthirsty Gladiator's Satin Robe",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "59",
		expansion = "",
	},
	60 = {
		source = "Rogoc",
		category_territory = "",
		name = "Bloodthirsty Gladiator's Silk Robe",
		territory = "Alliance",
		drop_rate = "Unknown",
		location = "Orgrimmar",
		id = "60",
		expansion = "",
	},
	61 = {
		source = "\",
		category_territory = "Dungeon",
		name = "Corsair's Overshirt",
		territory = "War Zone",
		drop_rate = "Unknown",
		location = "The Deadmines",
		id = "61",
		expansion = "",
	},
	62 = {
		source = "Echo of Tyrande",
		category_territory = "Dungeon",
		name = "Whisperwind Robes",
		territory = "Horde",
		drop_rate = "1.48",
		location = "End Time",
		id = "62",
		expansion = "Cataclysm",
	},
	63 = {
		source = "Crafter Kwon",
		category_territory = "",
		name = "Faded Forest Satin Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Timeless Isle",
		id = "63",
		expansion = "Mists Of Pandaria",
	},
	64 = {
		source = "Crafter Kwon",
		category_territory = "",
		name = "Faded Forest Silk Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Timeless Isle",
		id = "64",
		expansion = "Mists Of Pandaria",
	},
	65 = {
		source = "Hozen Groundpounder",
		category_territory = "",
		name = "Stitched Robe",
		territory = "Horde",
		drop_rate = "0.14",
		location = "The Jade Forest",
		id = "65",
		expansion = "Mists Of Pandaria",
	},
	66 = {
		source = "Riverblade Slayer",
		category_territory = "",
		name = "Reed Robe",
		territory = "Horde",
		drop_rate = "0.02",
		location = "Krasarang Wilds",
		id = "66",
		expansion = "Mists Of Pandaria",
	},
	67 = {
		source = "Seein Red",
		category_territory = "",
		name = "Silk Robe of Eminent Domain",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Jade Forest",
		id = "67",
		expansion = "Mists Of Pandaria",
	},
	68 = {
		source = "Seein Red",
		category_territory = "",
		name = "Satin Robe of Eminent Domain",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Jade Forest",
		id = "68",
		expansion = "Mists Of Pandaria",
	},
	69 = {
		source = "The Right Tool For The Job",
		category_territory = "",
		name = "Silk Robe of Eminent Domain",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Jade Forest",
		id = "69",
		expansion = "Mists Of Pandaria",
	},
	70 = {
		source = "The Right Tool For The Job",
		category_territory = "",
		name = "Satin Robe of Eminent Domain",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Jade Forest",
		id = "70",
		expansion = "Mists Of Pandaria",
	},
	71 = {
		source = "Mercy for the Bound",
		category_territory = "",
		name = "Fleshburned Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Twilight Highlands",
		id = "71",
		expansion = "Cataclysm",
	},
	72 = {
		source = "Tanithria",
		category_territory = "",
		name = "Deathsilk Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "72",
		expansion = "Legion",
	},
	73 = {
		source = "Scion of AlAkir",
		category_territory = "",
		name = "Robes of Whispering Sands",
		territory = "Horde",
		drop_rate = "0.0",
		location = "Uldum",
		id = "73",
		expansion = "Cataclysm",
	},
	74 = {
		source = "Spitebone Skeleton",
		category_territory = "Dungeon",
		name = "Bluefen Robe",
		territory = "Alliance",
		drop_rate = "0.08",
		location = "Shadowfang Keep",
		id = "74",
		expansion = "",
	},
	75 = {
		source = "The Curse of the Tombs",
		category_territory = "",
		name = "Robes of Khintaset",
		territory = "Horde",
		drop_rate = "quest",
		location = "Uldum",
		id = "75",
		expansion = "Cataclysm",
	},
	76 = {
		source = "Tailgunner!",
		category_territory = "",
		name = "Tailgunner's Flight Suit",
		territory = "Horde",
		drop_rate = "quest",
		location = "Uldum",
		id = "76",
		expansion = "Cataclysm",
	},
	77 = {
		source = "Romogg Bonecrusher",
		category_territory = "Dungeon",
		name = "Inquisition Robes",
		territory = "Horde",
		drop_rate = "16.07",
		location = "Blackrock Caverns",
		id = "77",
		expansion = "Cataclysm",
	},
	78 = {
		source = "Sins of the Sea Witch",
		category_territory = "Dungeon",
		name = "Deepmist Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Throne of the Tides",
		id = "78",
		expansion = "Cataclysm",
	},
	79 = {
		source = "Dark Iron Laborer",
		category_territory = "",
		name = "Robes of Broken Dreams",
		territory = "Horde",
		drop_rate = "0.01",
		location = "Mount Hyjal",
		id = "79",
		expansion = "Cataclysm",
	},
	80 = {
		source = "Tanithria",
		category_territory = "",
		name = "Spiritmend Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "80",
		expansion = "Legion",
	},
	81 = {
		source = "Highland Worg",
		category_territory = "",
		name = "Brightwood Robe",
		territory = "Horde",
		drop_rate = "0.02",
		location = "Twilight Highlands",
		id = "81",
		expansion = "Cataclysm",
	},
	82 = {
		source = "Dread Scryer",
		category_territory = "Dungeon",
		name = "Everstill Robe",
		territory = "Alliance",
		drop_rate = "0.06",
		location = "Shadowfang Keep",
		id = "82",
		expansion = "",
	},
	83 = {
		source = "Defias Digger",
		category_territory = "Dungeon",
		name = "Mystral Robe",
		territory = "War Zone",
		drop_rate = "0.07",
		location = "The Deadmines",
		id = "83",
		expansion = "",
	},
	84 = {
		source = "Resonating Blow",
		category_territory = "",
		name = "Stonescale Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Deepholm",
		id = "84",
		expansion = "Cataclysm",
	},
	85 = {
		source = "Idrakess Ambusher",
		category_territory = "",
		name = "Darrowmere Robe",
		territory = "Horde",
		drop_rate = "0.0",
		location = "Shimmering Expanse",
		id = "85",
		expansion = "Cataclysm",
	},
	86 = {
		source = "Elemental Energy",
		category_territory = "",
		name = "Sparklight Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Deepholm",
		id = "86",
		expansion = "Cataclysm",
	},
	87 = {
		source = "Prince Keleseth",
		category_territory = "Raid",
		name = "Sanguine Silk Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown Citadel",
		id = "87",
		expansion = "Wrath Of The Lich King",
	},
	88 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Dark Coven Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "88",
		expansion = "Legion",
	},
	89 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Crimson Acolyte Raiments",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "89",
		expansion = "Legion",
	},
	90 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Crimson Acolyte Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "90",
		expansion = "Legion",
	},
	91 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Bloodmage Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "91",
		expansion = "Legion",
	},
	92 = {
		source = "Twilight Zealot",
		category_territory = "Dungeon",
		name = "Mistmantle Robe",
		territory = "Horde",
		drop_rate = "0.13",
		location = "Blackrock Caverns",
		id = "92",
		expansion = "Cataclysm",
	},
	93 = {
		source = "Bloodsnarl Hyena",
		category_territory = "",
		name = "Baradin Robe",
		territory = "Horde",
		drop_rate = "0.01",
		location = "Uldum",
		id = "93",
		expansion = "Cataclysm",
	},
	94 = {
		source = "Twilight Zealot",
		category_territory = "Dungeon",
		name = "Ameth'Aran Robe",
		territory = "Horde",
		drop_rate = "0.11",
		location = "Blackrock Caverns",
		id = "94",
		expansion = "Cataclysm",
	},
	95 = {
		source = "The Earth Rises",
		category_territory = "",
		name = "Rockbreaker Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Mount Hyjal",
		id = "95",
		expansion = "Cataclysm",
	},
	96 = {
		source = "Orakos Report",
		category_territory = "",
		name = "Chum-Coated Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Abyssal Depths",
		id = "96",
		expansion = "Cataclysm",
	},
	97 = {
		source = "One Last Favor",
		category_territory = "",
		name = "Drag-Resistant Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Abyssal Depths",
		id = "97",
		expansion = "Cataclysm",
	},
	98 = {
		source = "Welcome News",
		category_territory = "",
		name = "Robes of the Watery Savior",
		territory = "Horde",
		drop_rate = "quest",
		location = "Shimmering Expanse",
		id = "98",
		expansion = "Cataclysm",
	},
	99 = {
		source = "Welcome News",
		category_territory = "",
		name = "Robes of the Watery Savior",
		territory = "Horde",
		drop_rate = "quest",
		location = "Shimmering Expanse",
		id = "99",
		expansion = "Cataclysm",
	},
	100 = {
		source = "Raw Materials",
		category_territory = "",
		name = "Abalone-Linked Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Kelp'thar Forest",
		id = "100",
		expansion = "Cataclysm",
	},
	101 = {
		source = "Gluth",
		category_territory = "Raid",
		name = "Robes of Hoarse Breaths",
		territory = "Horde",
		drop_rate = "0.66",
		location = "Naxxramas",
		id = "101",
		expansion = "Wrath Of The Lich King",
	},
	102 = {
		source = "Gluth",
		category_territory = "Raid",
		name = "Gown of Blaumeux",
		territory = "Horde",
		drop_rate = "1.79",
		location = "Naxxramas",
		id = "102",
		expansion = "Wrath Of The Lich King",
	},
	103 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Heroes' Frostfire Robe",
		territory = "Horde",
		drop_rate = "2.88",
		location = "Vault of Archavon",
		id = "103",
		expansion = "Wrath Of The Lich King",
	},
	104 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Heroes' Plagueheart Robe",
		territory = "Horde",
		drop_rate = "2.47",
		location = "Vault of Archavon",
		id = "104",
		expansion = "Wrath Of The Lich King",
	},
	105 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Heroes' Robe of Faith",
		territory = "Horde",
		drop_rate = "1.35",
		location = "Vault of Archavon",
		id = "105",
		expansion = "Wrath Of The Lich King",
	},
	106 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Heroes' Raiments of Faith",
		territory = "Horde",
		drop_rate = "1.21",
		location = "Vault of Archavon",
		id = "106",
		expansion = "Wrath Of The Lich King",
	},
	107 = {
		source = "Gluth",
		category_territory = "Raid",
		name = "Digested Silken Robes",
		territory = "Horde",
		drop_rate = "1.12",
		location = "Naxxramas",
		id = "107",
		expansion = "Wrath Of The Lich King",
	},
	108 = {
		source = "Gluth",
		category_territory = "Raid",
		name = "Heigan's Putrid Vestments",
		territory = "Horde",
		drop_rate = "1.49",
		location = "Naxxramas",
		id = "108",
		expansion = "Wrath Of The Lich King",
	},
	109 = {
		source = "Sapphiron",
		category_territory = "Raid",
		name = "Sympathy",
		territory = "Horde",
		drop_rate = "17.54",
		location = "Naxxramas",
		id = "109",
		expansion = "Wrath Of The Lich King",
	},
	110 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Valorous Frostfire Robe",
		territory = "Horde",
		drop_rate = "7.5",
		location = "Vault of Archavon",
		id = "110",
		expansion = "Wrath Of The Lich King",
	},
	111 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Valorous Plagueheart Robe",
		territory = "Horde",
		drop_rate = "6.41",
		location = "Vault of Archavon",
		id = "111",
		expansion = "Wrath Of The Lich King",
	},
	112 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Valorous Robe of Faith",
		territory = "Horde",
		drop_rate = "2.95",
		location = "Vault of Archavon",
		id = "112",
		expansion = "Wrath Of The Lich King",
	},
	113 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Valorous Raiments of Faith",
		territory = "Horde",
		drop_rate = "3.8",
		location = "Vault of Archavon",
		id = "113",
		expansion = "Wrath Of The Lich King",
	},
	114 = {
		source = "Gluth",
		category_territory = "Raid",
		name = "Robes of Mutation",
		territory = "Horde",
		drop_rate = "1.04",
		location = "Naxxramas",
		id = "114",
		expansion = "Wrath Of The Lich King",
	},
	115 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Hateful Gladiator's Mooncloth Robe",
		territory = "Horde",
		drop_rate = "1.26",
		location = "Vault of Archavon",
		id = "115",
		expansion = "Wrath Of The Lich King",
	},
	116 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Deadly Gladiator's Mooncloth Robe",
		territory = "Horde",
		drop_rate = "2.16",
		location = "Vault of Archavon",
		id = "116",
		expansion = "Wrath Of The Lich King",
	},
	117 = {
		source = "Kylo Kelwin",
		category_territory = "",
		name = "Furious Gladiator's Mooncloth Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "117",
		expansion = "Wrath Of The Lich King",
	},
	118 = {
		source = "Zom Bocom",
		category_territory = "",
		name = "Relentless Gladiator's Mooncloth Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "118",
		expansion = "Wrath Of The Lich King",
	},
	119 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Hateful Gladiator's Satin Robe",
		territory = "Horde",
		drop_rate = "1.6",
		location = "Vault of Archavon",
		id = "119",
		expansion = "Wrath Of The Lich King",
	},
	120 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Deadly Gladiator's Satin Robe",
		territory = "Horde",
		drop_rate = "4.66",
		location = "Vault of Archavon",
		id = "120",
		expansion = "Wrath Of The Lich King",
	},
	121 = {
		source = "Kylo Kelwin",
		category_territory = "",
		name = "Furious Gladiator's Satin Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "121",
		expansion = "Wrath Of The Lich King",
	},
	122 = {
		source = "Zom Bocom",
		category_territory = "",
		name = "Relentless Gladiator's Satin Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "122",
		expansion = "Wrath Of The Lich King",
	},
	123 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Hateful Gladiator's Silk Raiment",
		territory = "Horde",
		drop_rate = "2.77",
		location = "Vault of Archavon",
		id = "123",
		expansion = "Wrath Of The Lich King",
	},
	124 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Deadly Gladiator's Silk Raiment",
		territory = "Horde",
		drop_rate = "5.73",
		location = "Vault of Archavon",
		id = "124",
		expansion = "Wrath Of The Lich King",
	},
	125 = {
		source = "Kylo Kelwin",
		category_territory = "",
		name = "Furious Gladiator's Silk Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "125",
		expansion = "Wrath Of The Lich King",
	},
	126 = {
		source = "Zom Bocom",
		category_territory = "",
		name = "Relentless Gladiator's Silk Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "126",
		expansion = "Wrath Of The Lich King",
	},
	127 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Deadly Gladiator's Felweave Raiment",
		territory = "Horde",
		drop_rate = "5.0",
		location = "Vault of Archavon",
		id = "127",
		expansion = "Wrath Of The Lich King",
	},
	128 = {
		source = "Kylo Kelwin",
		category_territory = "",
		name = "Furious Gladiator's Felweave Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "128",
		expansion = "Wrath Of The Lich King",
	},
	129 = {
		source = "Zom Bocom",
		category_territory = "",
		name = "Relentless Gladiator's Felweave Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "129",
		expansion = "Wrath Of The Lich King",
	},
	130 = {
		source = "Archavon the Stone Watcher",
		category_territory = "Raid",
		name = "Hateful Gladiator's Felweave Raiment",
		territory = "Horde",
		drop_rate = "2.29",
		location = "Vault of Archavon",
		id = "130",
		expansion = "Wrath Of The Lich King",
	},
	131 = {
		source = "Tanithria",
		category_territory = "",
		name = "Moonshroud Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "131",
		expansion = "Legion",
	},
	132 = {
		source = "Tanithria",
		category_territory = "",
		name = "Ebonweave Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "132",
		expansion = "Legion",
	},
	133 = {
		source = "Tanithria",
		category_territory = "",
		name = "Spellweave Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "133",
		expansion = "Legion",
	},
	134 = {
		source = "Tanithria",
		category_territory = "",
		name = "Glacial Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "134",
		expansion = "Legion",
	},
	135 = {
		source = "Sartharion",
		category_territory = "Raid",
		name = "The Sanctum's Flowing Vestments",
		territory = "Horde",
		drop_rate = "16.1",
		location = "The Obsidian Sanctum",
		id = "135",
		expansion = "Wrath Of The Lich King",
	},
	136 = {
		source = "Archmage Alvareaux",
		category_territory = "",
		name = "Robes of Crackling Flame",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "136",
		expansion = "Wrath Of The Lich King",
	},
	137 = {
		source = "Runemaster Molgeim",
		category_territory = "Raid",
		name = "Raiments of the Iron Council",
		territory = "Horde",
		drop_rate = "20.39",
		location = "Ulduar",
		id = "137",
		expansion = "Wrath Of The Lich King",
	},
	138 = {
		source = "Paldesse",
		category_territory = "",
		name = "Valorous Kirin Tor Tunic",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "138",
		expansion = "Legion",
	},
	139 = {
		source = "Paldesse",
		category_territory = "",
		name = "Valorous Robe of Sanctification",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "139",
		expansion = "Legion",
	},
	140 = {
		source = "Paldesse",
		category_territory = "",
		name = "Valorous Raiments of Sanctification",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "140",
		expansion = "Legion",
	},
	141 = {
		source = "Paldesse",
		category_territory = "",
		name = "Valorous Deathbringer Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "141",
		expansion = "Legion",
	},
	142 = {
		source = "Auriaya",
		category_territory = "Raid",
		name = "Raiments of the Corrupted",
		territory = "Horde",
		drop_rate = "6.92",
		location = "Ulduar",
		id = "142",
		expansion = "Wrath Of The Lich King",
	},
	143 = {
		source = "General Vezax",
		category_territory = "Raid",
		name = "Vestments of the Piercing Light",
		territory = "Horde",
		drop_rate = "5.01",
		location = "Ulduar",
		id = "143",
		expansion = "Wrath Of The Lich King",
	},
	144 = {
		source = "Stone Guard Mukar",
		category_territory = "",
		name = "Titan-Forged Raiment of Dominance",
		territory = "",
		drop_rate = "Unknown",
		location = "Wintergrasp",
		id = "144",
		expansion = "Wrath Of The Lich King",
	},
	145 = {
		source = "Stone Guard Mukar",
		category_territory = "",
		name = "Titan-Forged Raiment of Salvation",
		territory = "",
		drop_rate = "Unknown",
		location = "Wintergrasp",
		id = "145",
		expansion = "Wrath Of The Lich King",
	},
	146 = {
		source = "Paldesse",
		category_territory = "",
		name = "Conqueror's Kirin Tor Tunic",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "146",
		expansion = "Legion",
	},
	147 = {
		source = "Paldesse",
		category_territory = "",
		name = "Conqueror's Deathbringer Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "147",
		expansion = "Legion",
	},
	148 = {
		source = "Paldesse",
		category_territory = "",
		name = "Conqueror's Raiments of Sanctification",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "148",
		expansion = "Legion",
	},
	149 = {
		source = "Paldesse",
		category_territory = "",
		name = "Conqueror's Robe of Sanctification",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "149",
		expansion = "Legion",
	},
	150 = {
		source = "Gormok the Impaler",
		category_territory = "Raid",
		name = "Flowing Vestments of Ascent",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "150",
		expansion = "Wrath Of The Lich King",
	},
	151 = {
		source = "Gormok the Impaler",
		category_territory = "Raid",
		name = "Flowing Vestments of Ascent",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "151",
		expansion = "Wrath Of The Lich King",
	},
	152 = {
		source = "Eydis Darkbane",
		category_territory = "Raid",
		name = "Skyweaver Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "152",
		expansion = "Wrath Of The Lich King",
	},
	153 = {
		source = "Eydis Darkbane",
		category_territory = "Raid",
		name = "Skyweaver Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "153",
		expansion = "Wrath Of The Lich King",
	},
	154 = {
		source = "Gormok the Impaler",
		category_territory = "Raid",
		name = "Flowing Robes of Ascent",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "154",
		expansion = "Wrath Of The Lich King",
	},
	155 = {
		source = "Eydis Darkbane",
		category_territory = "Raid",
		name = "Skyweaver Vestments",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "155",
		expansion = "Wrath Of The Lich King",
	},
	156 = {
		source = "Gormok the Impaler",
		category_territory = "Raid",
		name = "Flowing Robes of Ascent",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "156",
		expansion = "Wrath Of The Lich King",
	},
	157 = {
		source = "Eydis Darkbane",
		category_territory = "Raid",
		name = "Skyweaver Vestments",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "157",
		expansion = "Wrath Of The Lich King",
	},
	158 = {
		source = "The Black Knight",
		category_territory = "Dungeon",
		name = "Embrace of Madness",
		territory = "Horde",
		drop_rate = "11.47",
		location = "Crusaders' Coliseum: Trial of the Champion",
		id = "158",
		expansion = "Wrath Of The Lich King",
	},
	159 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Khadgar's Robe of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "159",
		expansion = "Legion",
	},
	160 = {
		source = "Valiant Laradia",
		category_territory = "",
		name = "Khadgar's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "160",
		expansion = "Wrath Of The Lich King",
	},
	161 = {
		source = "Champion Isimode",
		category_territory = "",
		name = "Khadgar's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "161",
		expansion = "Wrath Of The Lich King",
	},
	162 = {
		source = "Champion Faesrol",
		category_territory = "",
		name = "Sunstrider's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "162",
		expansion = "Wrath Of The Lich King",
	},
	163 = {
		source = "Valiant Bressia",
		category_territory = "",
		name = "Sunstrider's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "163",
		expansion = "Wrath Of The Lich King",
	},
	164 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sunstrider's Robe of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "164",
		expansion = "Legion",
	},
	165 = {
		source = "Valiant Laradia",
		category_territory = "",
		name = "Kel'Thuzad's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "165",
		expansion = "Wrath Of The Lich King",
	},
	166 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Kel'Thuzad's Robe of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "166",
		expansion = "Legion",
	},
	167 = {
		source = "Champion Isimode",
		category_territory = "",
		name = "Kel'Thuzad's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "167",
		expansion = "Wrath Of The Lich King",
	},
	168 = {
		source = "Champion Faesrol",
		category_territory = "",
		name = "Gul'dan's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "168",
		expansion = "Wrath Of The Lich King",
	},
	169 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Gul'dan's Robe of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "169",
		expansion = "Legion",
	},
	170 = {
		source = "Valiant Bressia",
		category_territory = "",
		name = "Gul'dan's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "170",
		expansion = "Wrath Of The Lich King",
	},
	171 = {
		source = "Anubarak",
		category_territory = "Raid",
		name = "Vestments of the Sleepless",
		territory = "Horde",
		drop_rate = "9.84",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "171",
		expansion = "Wrath Of The Lich King",
	},
	172 = {
		source = "Anubarak",
		category_territory = "Raid",
		name = "Robes of the Sleepless",
		territory = "Horde",
		drop_rate = "8.04",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "172",
		expansion = "Wrath Of The Lich King",
	},
	173 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Velen's Robe of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "173",
		expansion = "Legion",
	},
	174 = {
		source = "Anubarak",
		category_territory = "Raid",
		name = "Vestments of the Sleepless",
		territory = "Horde",
		drop_rate = "7.09",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "174",
		expansion = "Wrath Of The Lich King",
	},
	175 = {
		source = "Valiant Laradia",
		category_territory = "",
		name = "Velen's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "175",
		expansion = "Wrath Of The Lich King",
	},
	176 = {
		source = "Champion Isimode",
		category_territory = "",
		name = "Velen's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "176",
		expansion = "Wrath Of The Lich King",
	},
	177 = {
		source = "Anubarak",
		category_territory = "Raid",
		name = "Robes of the Sleepless",
		territory = "Horde",
		drop_rate = "6.35",
		location = "Crusaders' Coliseum: Trial of the Crusader",
		id = "177",
		expansion = "Wrath Of The Lich King",
	},
	178 = {
		source = "Champion Faesrol",
		category_territory = "",
		name = "Zabra's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "178",
		expansion = "Wrath Of The Lich King",
	},
	179 = {
		source = "Valiant Bressia",
		category_territory = "",
		name = "Zabra's Robe of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "179",
		expansion = "Wrath Of The Lich King",
	},
	180 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Zabra's Robe of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "180",
		expansion = "Legion",
	},
	181 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Velen's Raiments of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "181",
		expansion = "Legion",
	},
	182 = {
		source = "Valiant Laradia",
		category_territory = "",
		name = "Velen's Raiments of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "182",
		expansion = "Wrath Of The Lich King",
	},
	183 = {
		source = "Champion Isimode",
		category_territory = "",
		name = "Velen's Raiments of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "183",
		expansion = "Wrath Of The Lich King",
	},
	184 = {
		source = "Champion Faesrol",
		category_territory = "",
		name = "Zabra's Raiments of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "184",
		expansion = "Wrath Of The Lich King",
	},
	185 = {
		source = "Valiant Bressia",
		category_territory = "",
		name = "Zabra's Raiments of Triumph",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown",
		id = "185",
		expansion = "Wrath Of The Lich King",
	},
	186 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Zabra's Raiments of Conquest",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "186",
		expansion = "Legion",
	},
	187 = {
		source = "Scourgelord Tyrannus",
		category_territory = "Dungeon",
		name = "Palebone Robes",
		territory = "Horde",
		drop_rate = "2.07",
		location = "Pit of Saron",
		id = "187",
		expansion = "Wrath Of The Lich King",
	},
	188 = {
		source = "Prince Keleseth",
		category_territory = "Raid",
		name = "Sanguine Silk Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown Citadel",
		id = "188",
		expansion = "Wrath Of The Lich King",
	},
	189 = {
		source = "Devourer of Souls",
		category_territory = "Dungeon",
		name = "Mord'rethar Robes",
		territory = "Horde",
		drop_rate = "11.91",
		location = "The Forge of Souls",
		id = "189",
		expansion = "Wrath Of The Lich King",
	},
	190 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Dark Coven Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "190",
		expansion = "Legion",
	},
	191 = {
		source = "Krick",
		category_territory = "Dungeon",
		name = "Ancient Polar Bear Hide",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Pit of Saron",
		id = "191",
		expansion = "Wrath Of The Lich King",
	},
	192 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Bloodmage Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "192",
		expansion = "Legion",
	},
	193 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Crimson Acolyte Raiments",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "193",
		expansion = "Legion",
	},
	194 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Crimson Acolyte Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "194",
		expansion = "Legion",
	},
	195 = {
		source = "Paldesse",
		category_territory = "",
		name = "Meteor Chaser's Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "195",
		expansion = "Legion",
	},
	196 = {
		source = "Paldesse",
		category_territory = "",
		name = "Ermine Coronation Robes",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "196",
		expansion = "Legion",
	},
	197 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Bloodmage Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "197",
		expansion = "Legion",
	},
	198 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Crimson Acolyte Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "198",
		expansion = "Legion",
	},
	199 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Crimson Acolyte Raiments",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "199",
		expansion = "Legion",
	},
	200 = {
		source = "Cloth Merchant",
		category_territory = "",
		name = "Sanctified Dark Coven Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "200",
		expansion = "Legion",
	},
	201 = {
		source = "Prince Keleseth",
		category_territory = "Raid",
		name = "Bloodsoul Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown Citadel",
		id = "201",
		expansion = "Wrath Of The Lich King",
	},
	202 = {
		source = "Xazi Smolderpipe",
		category_territory = "",
		name = "Wrathful Gladiator's Silk Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "202",
		expansion = "Wrath Of The Lich King",
	},
	203 = {
		source = "Xazi Smolderpipe",
		category_territory = "",
		name = "Wrathful Gladiator's Mooncloth Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "203",
		expansion = "Wrath Of The Lich King",
	},
	204 = {
		source = "Xazi Smolderpipe",
		category_territory = "",
		name = "Wrathful Gladiator's Satin Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "204",
		expansion = "Wrath Of The Lich King",
	},
	205 = {
		source = "Xazi Smolderpipe",
		category_territory = "",
		name = "Wrathful Gladiator's Felweave Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "205",
		expansion = "Wrath Of The Lich King",
	},
	206 = {
		source = "Sindragosa",
		category_territory = "Raid",
		name = "Robes of Azure Downfall",
		territory = "Horde",
		drop_rate = "16.07",
		location = "Icecrown Citadel",
		id = "206",
		expansion = "Wrath Of The Lich King",
	},
	207 = {
		source = "Sindragosa",
		category_territory = "Raid",
		name = "Robes of Azure Downfall",
		territory = "Horde",
		drop_rate = "15.82",
		location = "Icecrown Citadel",
		id = "207",
		expansion = "Wrath Of The Lich King",
	},
	208 = {
		source = "Prince Keleseth",
		category_territory = "Raid",
		name = "Bloodsoul Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Icecrown Citadel",
		id = "208",
		expansion = "Wrath Of The Lich King",
	},
	209 = {
		source = "Stormcaller Brundir",
		category_territory = "Raid",
		name = "Raiments of the Iron Council",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Ulduar",
		id = "209",
		expansion = "Wrath Of The Lich King",
	},
	210 = {
		source = "Yogg-Saron",
		category_territory = "Raid",
		name = "Valorous Kirin Tor Tunic",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Ulduar",
		id = "210",
		expansion = "Wrath Of The Lich King",
	},
	211 = {
		source = "Yogg-Saron",
		category_territory = "Raid",
		name = "Valorous Robe of Sanctification",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Ulduar",
		id = "211",
		expansion = "Wrath Of The Lich King",
	},
	212 = {
		source = "Yogg-Saron",
		category_territory = "Raid",
		name = "Valorous Deathbringer Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Ulduar",
		id = "212",
		expansion = "Wrath Of The Lich King",
	},
	213 = {
		source = "Auriaya",
		category_territory = "Raid",
		name = "Raiments of the Corrupted",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Ulduar",
		id = "213",
		expansion = "Wrath Of The Lich King",
	},
	214 = {
		source = "General Vezax",
		category_territory = "Raid",
		name = "Vestments of the Piercing Light",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Ulduar",
		id = "214",
		expansion = "Wrath Of The Lich King",
	},
	215 = {
		source = "Sladran",
		category_territory = "Dungeon",
		name = "Embroidered Gown of Zul'Drak",
		territory = "Horde",
		drop_rate = "13.48",
		location = "Gundrak",
		id = "215",
		expansion = "Wrath Of The Lich King",
	},
	216 = {
		source = "Loken",
		category_territory = "Dungeon",
		name = "Raiments of the Titans",
		territory = "Horde",
		drop_rate = "6.25",
		location = "Halls of Lightning",
		id = "216",
		expansion = "Wrath Of The Lich King",
	},
	217 = {
		source = "Hadronox",
		category_territory = "Dungeon",
		name = "Egg Sac Robes",
		territory = "Horde",
		drop_rate = "6.12",
		location = "Azjol-Nerub",
		id = "217",
		expansion = "Wrath Of The Lich King",
	},
	218 = {
		source = "Drakos the Interrogator",
		category_territory = "Dungeon",
		name = "Drakewing Raiments",
		territory = "Horde",
		drop_rate = "15.04",
		location = "The Oculus",
		id = "218",
		expansion = "Wrath Of The Lich King",
	},
	219 = {
		source = "Galdarah",
		category_territory = "Dungeon",
		name = "Arcane Flame Altar-Garb",
		territory = "Horde",
		drop_rate = "3.76",
		location = "Gundrak",
		id = "219",
		expansion = "Wrath Of The Lich King",
	},
	220 = {
		source = "Loken",
		category_territory = "Dungeon",
		name = "Ornate Woolen Stola",
		territory = "Horde",
		drop_rate = "4.77",
		location = "Halls of Lightning",
		id = "220",
		expansion = "Wrath Of The Lich King",
	},
	221 = {
		source = "Tanithria",
		category_territory = "",
		name = "Black Duskweave Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "221",
		expansion = "Legion",
	},
	222 = {
		source = "Trapjaw Rix",
		category_territory = "",
		name = "Savage Gladiator's Mooncloth Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "222",
		expansion = "Wrath Of The Lich King",
	},
	223 = {
		source = "Trapjaw Rix",
		category_territory = "",
		name = "Savage Gladiator's Satin Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "223",
		expansion = "Wrath Of The Lich King",
	},
	224 = {
		source = "Trapjaw Rix",
		category_territory = "",
		name = "Savage Gladiator's Silk Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "224",
		expansion = "Wrath Of The Lich King",
	},
	225 = {
		source = "Trapjaw Rix",
		category_territory = "",
		name = "Savage Gladiator's Felweave Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "225",
		expansion = "Wrath Of The Lich King",
	},
	226 = {
		source = "Whatever it Takes!",
		category_territory = "Dungeon",
		name = "Robes of Lightning",
		territory = "Horde",
		drop_rate = "quest",
		location = "Halls of Lightning",
		id = "226",
		expansion = "Wrath Of The Lich King",
	},
	227 = {
		source = "Ichoron",
		category_territory = "Dungeon",
		name = "Water-Drenched Robe",
		territory = "Horde",
		drop_rate = "11.34",
		location = "The Violet Hold",
		id = "227",
		expansion = "Wrath Of The Lich King",
	},
	228 = {
		source = "Tanithria",
		category_territory = "",
		name = "Frostsavage Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "228",
		expansion = "Legion",
	},
	229 = {
		source = "Battle at Valhalas: Final Challenge",
		category_territory = "",
		name = "Robes of Refrained Celebration",
		territory = "Horde",
		drop_rate = "quest",
		location = "Icecrown",
		id = "229",
		expansion = "Wrath Of The Lich King",
	},
	230 = {
		source = "Junk in My Trunk",
		category_territory = "Dungeon",
		name = "Bauble-Woven Gown",
		territory = "Horde",
		drop_rate = "quest",
		location = "Utgarde Pinnacle",
		id = "230",
		expansion = "Wrath Of The Lich King",
	},
	231 = {
		source = "Ionar",
		category_territory = "Dungeon",
		name = "Ornate Woolen Stola",
		territory = "Horde",
		drop_rate = "5.1",
		location = "Halls of Lightning",
		id = "231",
		expansion = "Wrath Of The Lich King",
	},
	232 = {
		source = "Sladran",
		category_territory = "Dungeon",
		name = "Embroidered Gown of Zul'Drak",
		territory = "Horde",
		drop_rate = "2.18",
		location = "Gundrak",
		id = "232",
		expansion = "Wrath Of The Lich King",
	},
	233 = {
		source = "Galdarah",
		category_territory = "Dungeon",
		name = "Arcane Flame Altar-Garb",
		territory = "Horde",
		drop_rate = "5.34",
		location = "Gundrak",
		id = "233",
		expansion = "Wrath Of The Lich King",
	},
	234 = {
		source = "Auzin",
		category_territory = "",
		name = "Meteor Chaser's Raiment",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "234",
		expansion = "Wrath Of The Lich King",
	},
	235 = {
		source = "Scourgelord Tyrannus",
		category_territory = "Dungeon",
		name = "Palebone Robes",
		territory = "Horde",
		drop_rate = "5.39",
		location = "Pit of Saron",
		id = "235",
		expansion = "Wrath Of The Lich King",
	},
	236 = {
		source = "Meathook",
		category_territory = "Dungeon",
		name = "Vizier Robe",
		territory = "Horde",
		drop_rate = "0.17",
		location = "The Culling of Stratholme",
		id = "236",
		expansion = "Wrath Of The Lich King",
	},
	237 = {
		source = "Chrono-Lord Epoch",
		category_territory = "Dungeon",
		name = "Coldwraith Robe",
		territory = "Horde",
		drop_rate = "0.13",
		location = "The Culling of Stratholme",
		id = "237",
		expansion = "Wrath Of The Lich King",
	},
	238 = {
		source = "Iris Moondreamer",
		category_territory = "",
		name = "Magesoul Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Mount Hyjal",
		id = "238",
		expansion = "Cataclysm",
	},
	239 = {
		source = "Iris Moondreamer",
		category_territory = "",
		name = "Dreadsoul Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Mount Hyjal",
		id = "239",
		expansion = "Cataclysm",
	},
	240 = {
		source = "Iris Moondreamer",
		category_territory = "",
		name = "Seraphic Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Mount Hyjal",
		id = "240",
		expansion = "Cataclysm",
	},
	241 = {
		source = "Iris Moondreamer",
		category_territory = "",
		name = "Seraphic Vestments",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Mount Hyjal",
		id = "241",
		expansion = "Cataclysm",
	},
	242 = {
		source = "Krystallus",
		category_territory = "Dungeon",
		name = "Crystalsong Robe",
		territory = "Horde",
		drop_rate = "0.12",
		location = "Halls of Stone",
		id = "242",
		expansion = "Wrath Of The Lich King",
	},
	243 = {
		source = "Forging an Alliance",
		category_territory = "",
		name = "Vestments of Dun Niffelem",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Storm Peaks",
		id = "243",
		expansion = "Wrath Of The Lich King",
	},
	244 = {
		source = "Off With Their Black Wings",
		category_territory = "",
		name = "Flowing Valkyrion Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Storm Peaks",
		id = "244",
		expansion = "Wrath Of The Lich King",
	},
	245 = {
		source = "Taking on All Challengers",
		category_territory = "",
		name = "Hyldnir Runeweaver's Garb",
		territory = "Horde",
		drop_rate = "quest",
		location = "The Storm Peaks",
		id = "245",
		expansion = "Wrath Of The Lich King",
	},
	246 = {
		source = "Do Your Worst",
		category_territory = "",
		name = "Demolisher Driver's Dustcoat",
		territory = "Horde",
		drop_rate = "quest",
		location = "Icecrown",
		id = "246",
		expansion = "Wrath Of The Lich King",
	},
	247 = {
		source = "Novos the Summoner",
		category_territory = "Dungeon",
		name = "Robes of Novos",
		territory = "Horde",
		drop_rate = "21.48",
		location = "Drak'Tharon Keep",
		id = "247",
		expansion = "Wrath Of The Lich King",
	},
	248 = {
		source = "Mage-Lord Urom",
		category_territory = "Dungeon",
		name = "Condor Robe",
		territory = "Horde",
		drop_rate = "0.14",
		location = "The Oculus",
		id = "248",
		expansion = "Wrath Of The Lich King",
	},
	249 = {
		source = "Aces High!",
		category_territory = "",
		name = "Incursion Vestments",
		territory = "Horde",
		drop_rate = "quest",
		location = "Borean Tundra",
		id = "249",
		expansion = "Wrath Of The Lich King",
	},
	250 = {
		source = "Sairuk",
		category_territory = "",
		name = "Pigment-Stained Robes",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Dragonblight",
		id = "250",
		expansion = "Wrath Of The Lich King",
	},
	251 = {
		source = "Sairuk",
		category_territory = "",
		name = "Turtle-Minders Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Dragonblight",
		id = "251",
		expansion = "Wrath Of The Lich King",
	},
	252 = {
		source = "Drakkari Lancer",
		category_territory = "Dungeon",
		name = "Oracle Robe",
		territory = "Horde",
		drop_rate = "0.42",
		location = "Gundrak",
		id = "252",
		expansion = "Wrath Of The Lich King",
	},
	253 = {
		source = "Dark Rune Theurgist",
		category_territory = "Dungeon",
		name = "Aerie Robe",
		territory = "Horde",
		drop_rate = "0.1",
		location = "Halls of Stone",
		id = "253",
		expansion = "Wrath Of The Lich King",
	},
	254 = {
		source = "Flown the Coop!",
		category_territory = "",
		name = "Stained Coop Warmer",
		territory = "Horde",
		drop_rate = "quest",
		location = "Sholazar Basin",
		id = "254",
		expansion = "Wrath Of The Lich King",
	},
	255 = {
		source = "Exterminate the Intruders",
		category_territory = "",
		name = "Lifewarden's Raiment",
		territory = "Horde",
		drop_rate = "quest",
		location = "Sholazar Basin",
		id = "255",
		expansion = "Wrath Of The Lich King",
	},
	256 = {
		source = "Muru",
		category_territory = "Raid",
		name = "Fel Conqueror Raiments",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Sunwell Plateau",
		id = "256",
		expansion = "The Burning Crusade",
	},
	257 = {
		source = "Yrma",
		category_territory = "",
		name = "Robes of Ghostly Hatred",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Isle of Quel'Danas",
		id = "257",
		expansion = "",
	},
	258 = {
		source = "Blaze Magmaburn",
		category_territory = "",
		name = "Brutal Gladiator's Dreadweave Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "258",
		expansion = "The Burning Crusade",
	},
	259 = {
		source = "Blaze Magmaburn",
		category_territory = "",
		name = "Brutal Gladiator's Felweave Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "259",
		expansion = "The Burning Crusade",
	},
	260 = {
		source = "Blaze Magmaburn",
		category_territory = "",
		name = "Brutal Gladiator's Mooncloth Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "260",
		expansion = "The Burning Crusade",
	},
	261 = {
		source = "Blaze Magmaburn",
		category_territory = "",
		name = "Brutal Gladiator's Satin Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "261",
		expansion = "The Burning Crusade",
	},
	262 = {
		source = "Blaze Magmaburn",
		category_territory = "",
		name = "Brutal Gladiator's Silk Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "262",
		expansion = "The Burning Crusade",
	},
	263 = {
		source = "King Ping",
		category_territory = "",
		name = "Egg-Warming Blanket",
		territory = "Horde",
		drop_rate = "99.34",
		location = "Howling Fjord",
		id = "263",
		expansion = "Wrath Of The Lich King",
	},
	264 = {
		source = "Convocation at ZolHeb",
		category_territory = "",
		name = "Robe of the Conquered Prophet",
		territory = "Horde",
		drop_rate = "quest",
		location = "Zul'Drak",
		id = "264",
		expansion = "Wrath Of The Lich King",
	},
	265 = {
		source = "Lavanthor",
		category_territory = "Dungeon",
		name = "Tethys Robe",
		territory = "Horde",
		drop_rate = "0.2",
		location = "The Violet Hold",
		id = "265",
		expansion = "Wrath Of The Lich King",
	},
	266 = {
		source = "Precious Elemental Fluids",
		category_territory = "",
		name = "Bloodbinder's Raiment",
		territory = "Horde",
		drop_rate = "quest",
		location = "Zul'Drak",
		id = "266",
		expansion = "Wrath Of The Lich King",
	},
	267 = {
		source = "Too Much of a Good Thing",
		category_territory = "",
		name = "Soothsayer's Garb",
		territory = "Horde",
		drop_rate = "quest",
		location = "Zul'Drak",
		id = "267",
		expansion = "Wrath Of The Lich King",
	},
	268 = {
		source = "Tanithria",
		category_territory = "",
		name = "Duskweave Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "268",
		expansion = "Legion",
	},
	269 = {
		source = "Trolls Is Gone Crazy!",
		category_territory = "",
		name = "Emancipator's Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Zul'Drak",
		id = "269",
		expansion = "Wrath Of The Lich King",
	},
	270 = {
		source = "Muru",
		category_territory = "Raid",
		name = "Robes of Faltered Light",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Sunwell Plateau",
		id = "270",
		expansion = "The Burning Crusade",
	},
	271 = {
		source = "Risen Drakkari Warrior",
		category_territory = "Dungeon",
		name = "Icemist Robe",
		territory = "Horde",
		drop_rate = "0.11",
		location = "Drak'Tharon Keep",
		id = "271",
		expansion = "Wrath Of The Lich King",
	},
	272 = {
		source = "Souls at Unrest",
		category_territory = "",
		name = "Specially Treated Robes",
		territory = "Horde",
		drop_rate = "quest",
		location = "Grizzly Hills",
		id = "272",
		expansion = "Wrath Of The Lich King",
	},
	273 = {
		source = "Archimonde",
		category_territory = "Raid",
		name = "Robes of Rhonin",
		territory = "Horde",
		drop_rate = "18.88",
		location = "Hyjal Summit",
		id = "273",
		expansion = "The Burning Crusade",
	},
	274 = {
		source = "Tanithria",
		category_territory = "",
		name = "Mystic Frostwoven Robe",
		territory = "",
		drop_rate = "Unknown",
		location = "Dalaran",
		id = "274",
		expansion = "Legion",
	},
	275 = {
		source = "Plundering Geist",
		category_territory = "Dungeon",
		name = "Voldrune Robe",
		territory = "Horde",
		drop_rate = "0.09",
		location = "Ahn'kahet: The Old Kingdom",
		id = "275",
		expansion = "Wrath Of The Lich King",
	},
	276 = {
		source = "Tydormu",
		category_territory = "Raid",
		name = "Robe of the Malefic",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Hyjal Summit",
		id = "276",
		expansion = "The Burning Crusade",
	},
	277 = {
		source = "Tydormu",
		category_territory = "Raid",
		name = "Robes of the Tempest",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Hyjal Summit",
		id = "277",
		expansion = "The Burning Crusade",
	},
	278 = {
		source = "Tydormu",
		category_territory = "Raid",
		name = "Shroud of Absolution",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Hyjal Summit",
		id = "278",
		expansion = "The Burning Crusade",
	},
	279 = {
		source = "Tydormu",
		category_territory = "Raid",
		name = "Vestments of Absolution",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Hyjal Summit",
		id = "279",
		expansion = "The Burning Crusade",
	},
	280 = {
		source = "Kitzie Crankshot",
		category_territory = "",
		name = "Vengeful Gladiator's Dreadweave Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "280",
		expansion = "The Burning Crusade",
	},
	281 = {
		source = "Kitzie Crankshot",
		category_territory = "",
		name = "Vengeful Gladiator's Felweave Raiment",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "281",
		expansion = "The Burning Crusade",
	},
	282 = {
		source = "Kitzie Crankshot",
		category_territory = "",
		name = "Vengeful Gladiator's Mooncloth Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "282",
		expansion = "The Burning Crusade",
	},
	283 = {
		source = "Kitzie Crankshot",
		category_territory = "",
		name = "Vengeful Gladiator's Satin Robe",
		territory = "Horde",
		drop_rate = "Unknown",
		location = "Netherstorm",
		id = "283",
		expansion = "The Burning Crusade",
	},
	lol = "d"
}