cloth-hand_url_db = {
	0 = {
		category_territory = "",
		drop_rate = "0.26",
		location = "Darkshore",
		id = "0",
		name = "Moonpriest's Handwraps",
		expansion = "",
		source = "Granokk",
		territory = "War Zone",
	},
	1 = {
		category_territory = "",
		drop_rate = "0.7",
		location = "Darkshore",
		id = "1",
		name = "Plaguebringer's Gloves",
		expansion = "",
		source = "Aman",
		territory = "War Zone",
	},
	2 = {
		category_territory = "Raid",
		drop_rate = "1.34",
		location = "Uldir",
		id = "2",
		name = "Spellbound Specimen Handlers",
		expansion = "Battle For Azeroth",
		source = "Nazmani Veinsplitter",
		territory = "Horde",
	},
	3 = {
		category_territory = "Raid",
		drop_rate = "2.26",
		location = "Uldir",
		id = "3",
		name = "Mutagenic Protofluid Handwraps",
		expansion = "Battle For Azeroth",
		source = "Vectis",
		territory = "Horde",
	},
	4 = {
		category_territory = "",
		drop_rate = "Unknown",
		location = "Tiragarde Sound",
		id = "4",
		name = "Windcaller's Down Handwraps",
		expansion = "Battle For Azeroth",
		source = "Azurethos",
		territory = "Horde",
	},
	5 = {
		category_territory = "Outdoor Zone",
		drop_rate = "Unknown",
		location = "Zuldazar",
		id = "5",
		name = "Gloves of Enveloping Winds",
		expansion = "Battle For Azeroth",
		source = "Jiarak",
		territory = "Horde",
	},
	6 = {
		category_territory = "Outdoor Zone",
		drop_rate = "Unknown",
		location = "Nazmir",
		id = "6",
		name = "Zo'bal Spirit Gloves",
		expansion = "Battle For Azeroth",
		source = "Provisioner Lija",
		territory = "Horde",
	},
	7 = {
		category_territory = "",
		drop_rate = "Unknown",
		location = "Drustvar",
		id = "7",
		name = "Eternal Flamekeeper's Handwraps",
		expansion = "Battle For Azeroth",
		source = "Quartermaster Alcorn",
		territory = "Horde",
	},
	8 = {
		category_territory = "Outdoor Zone",
		drop_rate = "0.02",
		location = "Vol'dun",
		id = "8",
		name = "Hauer's Gloves of Strategy",
		expansion = "Battle For Azeroth",
		source = "Faithless Aggressor",
		territory = "Horde",
	},
	9 = {
		category_territory = "Outdoor Zone",
		drop_rate = "Unknown",
		location = "Vol'dun",
		id = "9",
		name = "Gloves of the Scaled Devoted",
		expansion = "Battle For Azeroth",
		source = "Hoarder Jena",
		territory = "Horde",
	},
	10 = {
		category_territory = "Raid",
		drop_rate = "Unknown",
		location = "Battle of Dazar'alor",
		id = "10",
		name = "Manceroy's Flamefists",
		expansion = "Battle For Azeroth",
		source = "Manceroy Flamefist",
		territory = "Horde",
	},
	11 = {
		category_territory = "Raid",
		drop_rate = "Unknown",
		location = "Battle of Dazar'alor",
		id = "11",
		name = "Firecaller's Handwraps",
		expansion = "Battle For Azeroth",
		source = "Mara Grimfang",
		territory = "Horde",
	},
	12 = {
		category_territory = "Outdoor Zone",
		drop_rate = "Unknown",
		location = "Vol'dun",
		id = "12",
		name = "Alpaca Wool Gloves",
		expansion = "Battle For Azeroth",
		source = "Hoarder Jena",
		territory = "Horde",
	},
	13 = {
		category_territory = "",
		drop_rate = "Unknown",
		location = "Stormsong Valley",
		id = "13",
		name = "Handwraps of Deep Faith",
		expansion = "Battle For Azeroth",
		source = "Sister Lilyana",
		territory = "Horde",
	},
	14 = {
		category_territory = "Outdoor Zone",
		drop_rate = "Unknown",
		location = "Nazmir",
		id = "14",
		name = "Swamp Medic's Gloves",
		expansion = "Battle For Azeroth",
		source = "Provisioner Lija",
		territory = "Horde",
	},
